# Generated by Django 5.0.4 on 2026-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('warehouse_id', models.IntegerField(blank=True, db_column='warehouse_id', db_index=True, null=True, verbose_name='شناسهٔ انبار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'warehouses_systemsetting',
                'unique_together': {('key', 'warehouse_id')},
            },
        ),
    ]
