# Generated by Django 5.0.4 on 2026-07-06 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('conflict_strategy', models.CharField(default='ignore', max_length=50)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_unic_code', models.CharField(max_length=100, unique=True, verbose_name='کد یکتا (FA-UNIC)')),
                ('plpkitem', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد ترکیبی PL-PK-Item')),
                ('pl', models.CharField(blank=True, max_length=100, null=True, verbose_name='پکینگ لیست (PL)')),
                ('po', models.CharField(blank=True, max_length=100, null=True, verbose_name='سفارش خرید (PO)')),
                ('pk_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='پکیج (PK)')),
                ('item_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ردیف (Item)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='شرح کالا')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='واحد سنجش')),
                ('scope_discipline', models.CharField(blank=True, max_length=100, null=True, verbose_name='دیسیپلین کاری')),
                ('balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, verbose_name='موجودی فیزیکی')),
                ('bal4miv', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, verbose_name='موجودی مجاز MIV')),
                ('old_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='لوکیشن قبلی')),
                ('new_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='لوکیشن جدید')),
                ('hov_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره HOV')),
                ('hov_date', models.DateField(blank=True, null=True, verbose_name='تاریخ HOV')),
                ('msr_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت MSR')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True, verbose_name='سازنده (Vendor)')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='تامین کننده (Supplier)')),
                ('irn_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره IRN')),
                ('item2', models.CharField(blank=True, max_length=100, null=True, verbose_name='ردیف فرعی (ITEM2)')),
                ('inventory_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='طبقه\u200cبندی انبار')),
                ('indent', models.CharField(blank=True, max_length=100, null=True, verbose_name='تقاضای خرید (INDENT)')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='مبلغ')),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='ارز')),
                ('invoice_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس فایل فاکتور')),
                ('invoice_page', models.CharField(blank=True, max_length=100, null=True, verbose_name='صفحه فاکتور')),
                ('customs_field', models.CharField(blank=True, max_length=255, null=True, verbose_name='فیلد گمرکی')),
                ('customs_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس فایل گمرکی')),
                ('customs_file_page', models.CharField(blank=True, max_length=100, null=True, verbose_name='صفحه گمرک')),
                ('price_remark', models.TextField(blank=True, null=True, verbose_name='توضیحات قیمت')),
                ('issue_remark', models.TextField(blank=True, null=True, verbose_name='ملاحظات صدور (Issue Remark)')),
                ('tag_status', models.CharField(default='چاپ نشده', max_length=50, verbose_name='وضعیت لیبل')),
                ('field_status', models.CharField(default='در انتظار شمارش', max_length=50, verbose_name='وضعیت میدانی')),
                ('doc_status', models.CharField(default='عدم تطابق', max_length=50, verbose_name='وضعیت مستندات')),
                ('has_conflict', models.BooleanField(default=False, verbose_name='مغایرت دارد')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='شکستنی')),
                ('is_heavy', models.BooleanField(default=False, verbose_name='سنگین')),
                ('needs_qc', models.BooleanField(default=False, verbose_name='نیاز به کنترل کیفی')),
                ('tag', models.CharField(blank=True, max_length=500, null=True, verbose_name='تگ\u200cها')),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='محول شده به')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_items', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouses.warehouse', verbose_name='انبار')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_photos/')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_item_photos', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.item')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_item_photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
