# Generated by Django 5.0.4 on 2026-07-03 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('part_no', models.CharField(max_length=100)),
                ('mesc', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_status', models.CharField(default='چاپ نشده', max_length=50)),
                ('field_status', models.CharField(default='در انتظار شمارش', max_length=50)),
                ('doc_status', models.CharField(default='عدم تطابق', max_length=50)),
                ('has_conflict', models.BooleanField(default=False)),
                ('is_fragile', models.BooleanField(default=False)),
                ('is_heavy', models.BooleanField(default=False)),
                ('needs_qc', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='warehouses.warehouse')),
            ],
        ),
    ]
