# Generated by Django 5.0.4 on 2026-07-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fa_unic_code',
            field=models.CharField(max_length=100, verbose_name='کد یکتا (FA-UNIC)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='plpkitem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد ترکیبی PL-PK-Item'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('warehouse', 'fa_unic_code')},
        ),
    ]
