# Generated by Django 5.0.4 on 2026-09-13 18:51

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctask',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='doctask',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='doctask',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده (نرم)'),
        ),
    ]
