# Generated by Django 5.0.4 on 2026-07-06 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_fa_unic_code_alter_item_plpkitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='import_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه یکتای فرآیند'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='is_reverted',
            field=models.BooleanField(default=False, verbose_name='بازگردانی شده'),
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('import_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='inventory.importlog')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
    ]
