# Generated by Django 5.0.4 on 2026-09-27 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_doctask_options_alter_doctask_managers_and_more'),
        ('personnel', '0021_remove_monthlyworkperiod_unique_warehouse_year_month_period_and_more'),
        ('warehouses', '0004_remove_warehouse_company_id_warehouse_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemfielddefinition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemfielddefinition',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_field_definitions', to='personnel.company', verbose_name='شرکت متبوع'),
        ),
        migrations.AddConstraint(
            model_name='itemfielddefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False), ('warehouse__isnull', False)), fields=('company', 'warehouse', 'name'), name='unique_company_warehouse_field_def'),
        ),
        migrations.AddConstraint(
            model_name='itemfielddefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False), ('warehouse__isnull', True)), fields=('company', 'name'), name='unique_company_field_def'),
        ),
        migrations.AddConstraint(
            model_name='itemfielddefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('warehouse', 'name'), name='unique_warehouse_field_def'),
        ),
    ]
