# Generated by Django 5.0.4 on 2026-07-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_importlog_import_id_importlog_is_reverted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='item',
            name='doc_assignee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محول شده به (مدارک و قیمت)'),
        ),
        migrations.AddField(
            model_name='item',
            name='field_assignee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محول شده به (میدانی)'),
        ),
    ]
