# Generated by Django 5.0.4 on 2026-07-08 22:34

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_item_assigned_to_item_doc_assignee_and_more'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='item_desc_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fa_unic_code'], name='item_code_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
