# Generated by Django 5.0.4 on 2026-07-10 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_item_desc_gin_idx_item_item_code_gin_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_COUNT', 'در انتظار شمارش'), ('COUNTED', 'شمارش شده (نزد سرپرست)'), ('SUPERVISOR_REJECTED', 'رد شده توسط سرپرست'), ('MANAGER_REVIEW', 'در انتظار تایید مدیر'), ('MANAGER_REJECTED', 'درخواست بازشماری (رد مدیر)'), ('FINAL_APPROVED', 'تایید نهایی')], default='PENDING_COUNT', max_length=50, verbose_name='وضعیت')),
                ('counted_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='مقدار شمرده شده')),
                ('counter_note', models.TextField(blank=True, null=True, verbose_name='توضیحات شمارشگر')),
                ('supervisor_note', models.TextField(blank=True, null=True, verbose_name='توضیحات سرپرست')),
                ('manager_note', models.TextField(blank=True, null=True, verbose_name='توضیحات مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_tasks', to=settings.AUTH_USER_MODEL, verbose_name='شمارشگر')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_count_tasks', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_tasks', to='inventory.item', verbose_name='کالا')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_count_tasks', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_tasks', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
