# Generated by Django 5.0.4 on 2026-07-11 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_counttask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='نوع اقدام')),
                ('counted_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='مقدار شمرده شده (Snapshot)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات در لحظه ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_histories', to=settings.AUTH_USER_MODEL, verbose_name='اقدام کننده')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.counttask', verbose_name='تسک شمارش')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
