# Generated by Django 5.0.4 on 2026-07-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_counttaskhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='doc_status',
            field=models.CharField(default='waiting', max_length=50, verbose_name='وضعیت مستندات'),
        ),
        migrations.AlterField(
            model_name='item',
            name='field_status',
            field=models.CharField(default='waiting', max_length=50, verbose_name='وضعیت میدانی'),
        ),
    ]
