# Generated by Django 5.0.4 on 2026-07-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_counttask_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counttask',
            name='skip_supervisor',
            field=models.BooleanField(default=False, verbose_name='بدون نیاز به سرپرست'),
        ),
    ]
