# Generated by Django 5.0.4 on 2026-07-22 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_counttask_skip_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_DOC', 'در انتظار اسناد'), ('DOC_PROCESSED', 'بررسی شده (توسط بررسی\u200cکننده)'), ('DOC_SUPERVISOR_REJECTED', 'رد شده توسط سرپرست اسناد'), ('DOC_MANAGER_REVIEW', 'در انتظار تایید مدیر'), ('DOC_MANAGER_REJECTED', 'مغایرت تاییدشده (رد مدیر)'), ('DOC_FINAL_APPROVED', 'تایید نهایی')], default='PENDING_DOC', max_length=50, verbose_name='وضعیت')),
                ('skip_supervisor', models.BooleanField(default=False, verbose_name='بدون نیاز به سرپرست اسناد')),
                ('worker_note', models.TextField(blank=True, null=True, verbose_name='توضیحات بررسی\u200cکننده')),
                ('supervisor_note', models.TextField(blank=True, null=True, verbose_name='توضیحات سرپرست اسناد')),
                ('manager_note', models.TextField(blank=True, null=True, verbose_name='توضیحات مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_assigned_manager_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مدیر ارجاع\u200cدهنده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_tasks', to=settings.AUTH_USER_MODEL)),
                ('doc_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_supervisor_tasks', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست اسناد')),
                ('doc_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_worker_tasks', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_tasks', to='inventory.item', verbose_name='کالا')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_doc_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='نوع عملیات')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت در زمان ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_action_histories', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.doctask', verbose_name='تسک اسناد')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
