# Generated by Django 5.0.4 on 2026-07-23 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_doctask_doctaskhistory'),
        ('warehouses', '0002_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dynamic_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='اطلاعات متغیر (پویا)'),
        ),
        migrations.CreateModel(
            name='ItemFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سیستمی فیلد (انگلیسی)')),
                ('label', models.CharField(max_length=200, verbose_name='عنوان نمایشی (فارسی)')),
                ('field_type', models.CharField(choices=[('text', 'متن (Text)'), ('number', 'عدد (Number)'), ('boolean', 'چک\u200cباکس (Boolean)'), ('date', 'تاریخ (Date)')], default='text', max_length=50, verbose_name='نوع داده')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار پیش\u200cفرض')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_field_defs', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='warehouses.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'تعریف فیلد پویا',
                'verbose_name_plural': 'تعاریف فیلدهای پویا',
                'ordering': ['created_at'],
                'unique_together': {('warehouse', 'name')},
            },
        ),
    ]
