# Generated by Django 5.0.4 on 2026-07-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_item_dynamic_data_itemfielddefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfielddefinition',
            name='field_type',
            field=models.CharField(choices=[('text', 'متن (Text)'), ('number', 'عدد (Number)'), ('boolean', 'بله/خیر (Boolean)'), ('date', 'تاریخ (Date)')], default='text', max_length=20, verbose_name='نوع داده'),
        ),
        migrations.AlterField(
            model_name='itemfielddefinition',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='اجباری است؟'),
        ),
        migrations.AlterField(
            model_name='itemfielddefinition',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام سیستمی (انگلیسی)'),
        ),
    ]
