# Generated by Django 5.0.4 on 2026-08-02 11:28

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_sync_fields_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counttask',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='counttaskhistory',
            options={'base_manager_name': 'all_objects', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='itemfielddefinition',
            options={'base_manager_name': 'all_objects', 'ordering': ['created_at'], 'verbose_name': 'تعریف فیلد پویا', 'verbose_name_plural': 'تعاریف فیلدهای پویا'},
        ),
        migrations.AlterModelManagers(
            name='counttask',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='counttaskhistory',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='itemfielddefinition',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
