# Generated by Django 5.0.4 on 2026-08-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_rename_balance_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='customs_field',
        ),
        migrations.RemoveField(
            model_name='item',
            name='customs_file',
        ),
        migrations.RemoveField(
            model_name='item',
            name='customs_file_page',
        ),
        migrations.RemoveField(
            model_name='item',
            name='inventory_status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='invoice_file',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_fragile',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_heavy',
        ),
        migrations.RemoveField(
            model_name='item',
            name='issue_remark',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='needs_qc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='old_location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='plpkitem',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_remark',
        ),
    ]
