# Generated by Django 5.0.4 on 2026-08-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_unused_item_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_rti_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره RTI افزوده\u200cشده'),
        ),
        migrations.AddField(
            model_name='item',
            name='doc_supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تامین\u200cکننده فاکتور (Supplier)'),
        ),
        migrations.AddField(
            model_name='item',
            name='folder_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='مسیر پوشه اسناد'),
        ),
        migrations.AddField(
            model_name='item',
            name='hyperlink',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='هایپرلینک اسناد'),
        ),
        migrations.AddField(
            model_name='item',
            name='inv_rti_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره RTI فاکتور'),
        ),
        migrations.AddField(
            model_name='item',
            name='invoice_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ فاکتور'),
        ),
        migrations.AddField(
            model_name='item',
            name='invoice_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع فاکتور'),
        ),
        migrations.AddField(
            model_name='item',
            name='page_row',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ردیف در فاکتور'),
        ),
        migrations.AddField(
            model_name='item',
            name='request_number_of_table',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره درخواست جدول'),
        ),
        migrations.AddField(
            model_name='item',
            name='similar_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='قیمت کالای مشابه'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سایز اصلی'),
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تگ کالا'),
        ),
        migrations.AddField(
            model_name='item',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='ارزش کل'),
        ),
        migrations.AlterField(
            model_name='item',
            name='invoice_page',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صفحه فاکتور (PageNumber)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='قیمت واحد (UnitPrice)'),
        ),
    ]
