# Generated by Django 5.0.4 on 2026-08-07 18:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_add_excel_item_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctask',
            name='added_rti_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره RTI اضافه\u200cشده'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='currency',
            field=models.CharField(blank=True, choices=[('IRR', 'ریال'), ('USD', 'دلار'), ('EUR', 'یورو'), ('OTHER', 'سایر')], max_length=10, null=True, verbose_name='ارز'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='doc_supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تأمین\u200cکننده'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='folder_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس پوشه'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='inv_rti_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره RTI فاکتور'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ فاکتور'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='invoice_page',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='صفحه فاکتور'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('formal', 'رسمی/مالیاتی'), ('domestic', 'خریدهای داخلی'), ('foreign', 'خریدهای خارجی'), ('consignment', 'امانی')], max_length=20, null=True, verbose_name='نوع فاکتور'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='page_row',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ردیف صفحه'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='signature',
            field=models.BooleanField(default=False, verbose_name='امضا'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='similar_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='قیمت مشابه'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='stamp',
            field=models.BooleanField(default=False, verbose_name='مهر'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='sync_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه سینک'),
        ),
        migrations.AddField(
            model_name='doctask',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='ارزش کل'),
        ),
        migrations.AddField(
            model_name='item',
            name='desc_from_standard_system',
            field=models.TextField(blank=True, null=True, verbose_name='شرح کالا در سامانه یکنواخت'),
        ),
        migrations.AddField(
            model_name='item',
            name='signature',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='وضعیت امضای اسناد'),
        ),
        migrations.AddField(
            model_name='item',
            name='stamp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='وضعیت مهر اسناد'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_from_standard_system',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='واحد کالا در سامانه یکنواخت'),
        ),
    ]
