# Generated by Django 5.0.4 on 2026-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_add_financial_fields_to_doctask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counttask',
            name='status',
            field=models.CharField(choices=[('PENDING_COUNT', 'در انتظار شمارش'), ('INITIAL_COUNT', 'شمارش اولیه (ثبت موقت)'), ('COUNTED', 'شمارش شده (نزد سرپرست)'), ('SUPERVISOR_REJECTED', 'رد شده توسط سرپرست'), ('MANAGER_REVIEW', 'در انتظار تایید مدیر'), ('MANAGER_REJECTED', 'درخواست بازشماری (رد مدیر)'), ('FINAL_APPROVED', 'تایید نهایی')], default='PENDING_COUNT', max_length=50, verbose_name='وضعیت'),
        ),
    ]
