# Generated by Django 5.0.4 on 2026-08-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_counttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctaskhistory',
            name='data_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='اسنپ\u200cشات اطلاعات در لحظه عملیات'),
        ),
    ]
