# Generated by Django 5.0.4 on 2026-08-21 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_doctaskhistory_data_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='counttaskhistory',
            name='counted_balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='مقدار شمرده شده'),
        ),
        migrations.AlterField(
            model_name='item',
            name='bal4miv',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15, verbose_name='موجودی مجاز'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='item',
            name='doc_assignee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محول شده به مدارک و قیمت'),
        ),
        migrations.AlterField(
            model_name='item',
            name='doc_supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تامین\u200cکننده فاکتور'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dynamic_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='اطلاعات متغیر'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fa_unic_code',
            field=models.CharField(max_length=100, verbose_name='کد یکتا'),
        ),
        migrations.AlterField(
            model_name='item',
            name='field_assignee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محول شده به میدانی'),
        ),
        migrations.AlterField(
            model_name='item',
            name='indent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تقاضای خرید'),
        ),
        migrations.AlterField(
            model_name='item',
            name='invoice_page',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صفحه فاکتور'),
        ),
        migrations.AlterField(
            model_name='item',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_items', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pk_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پکیج'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پکینگ لیست'),
        ),
        migrations.AlterField(
            model_name='item',
            name='po',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سفارش خرید'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تامین کننده'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سازنده'),
        ),
    ]
