# Generated by Django 5.0.4 on 2026-08-23 16:20

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_counttaskhistory_counted_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemphoto',
            options={'base_manager_name': 'all_objects', 'ordering': ['display_order', '-is_primary', '-created_at'], 'verbose_name': 'عکس کالا', 'verbose_name_plural': 'عکس\u200cهای کالا'},
        ),
        migrations.AlterModelManagers(
            name='itemphoto',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='itemphoto',
            old_name='description',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='count_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_photos', to='inventory.counttask', verbose_name='تسک شمارش مرتبط'),
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='حجم فایل (بایت)'),
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='ارتفاع'),
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده (نرم)'),
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='تصویر شاخص'),
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='medium',
            field=models.ImageField(blank=True, null=True, upload_to='item_photos/medium/%Y/%m/', verbose_name='تصویر متوسط'),
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='source_type',
            field=models.CharField(choices=[('camera', 'دوربین انبار'), ('gallery', 'گالری / فایل')], default='gallery', max_length=20, verbose_name='منبع تصویر'),
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='sync_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه همگام\u200cسازی'),
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='item_photos/thumbnails/%Y/%m/', verbose_name='بندانگشتی'),
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='width',
            field=models.PositiveIntegerField(default=0, verbose_name='عرض'),
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_item_photos', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='image',
            field=models.ImageField(upload_to='item_photos/originals/%Y/%m/', verbose_name='تصویر اصلی (WebP)'),
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.item', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_item_photos', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
