# Generated by Django 5.0.4 on 2026-08-23 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_itemphoto_options_alter_itemphoto_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemphoto',
            options={'base_manager_name': 'all_objects', 'ordering': ['-is_primary', 'display_order', '-created_at', '-id'], 'verbose_name': 'عکس کالا', 'verbose_name_plural': 'عکس\u200cهای کالا'},
        ),
        migrations.AddIndex(
            model_name='itemphoto',
            index=models.Index(fields=['item', 'is_deleted', '-is_primary', 'display_order'], name='itemphoto_item_live_order_idx'),
        ),
    ]
