# Generated by Django 5.0.4 on 2026-08-03 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0003_add_label_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(default='report', max_length=200, verbose_name='نام گزارش')),
                ('spec', models.JSONField(default=dict, verbose_name='تعریف گزارش')),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('running', 'در حال تولید'), ('done', 'آماده دانلود'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='تعداد کل ردیف\u200cها')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسیر فایل (نسبی)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='متن خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کار خروجی گزارش',
                'verbose_name_plural': 'کارهای خروجی گزارش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام گزارش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('entity', models.CharField(max_length=50, verbose_name='موجودیت (کلید رجیستری)')),
                ('spec', models.JSONField(default=dict, verbose_name='تعریف گزارش')),
                ('is_public', models.BooleanField(default=False, verbose_name='اشتراک\u200cگذاری عمومی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='warehouses.warehouse', verbose_name='انبار (برای فیلدهای پویا)')),
            ],
            options={
                'verbose_name': 'قالب گزارش',
                'verbose_name_plural': 'قالب\u200cهای گزارش',
                'ordering': ['-updated_at'],
            },
        ),
    ]
