# Generated by Django 5.0.4 on 2026-08-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_export_worker_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportexportjob',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش'),
        ),
    ]
