# Generated by Django 5.0.4 on 2026-09-08 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='account_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='کد حساب تفصیلی (رزرو دفتر کل)'),
        ),
        migrations.CreateModel(
            name='AccountingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_model', models.CharField(db_index=True, max_length=100, verbose_name='مدل مبدا')),
                ('source_id', models.CharField(db_index=True, max_length=100, verbose_name='شناسه رکورد مبدا')),
                ('event_type', models.CharField(db_index=True, max_length=50, verbose_name='نوع رویداد مالی')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان وقوع')),
                ('payload', models.JSONField(default=dict, verbose_name='داده\u200cهای رویداد و آرتیکل\u200cهای سند')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان ثبت قطعی در دفتر کل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رویداد مالی (Outbox)',
                'verbose_name_plural': 'رویدادهای مالی (Outbox)',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['source_model', 'source_id'], name='personnel_a_source__a41041_idx'), models.Index(fields=['event_type', 'occurred_at'], name='personnel_a_event_t_5f0deb_idx')],
            },
        ),
    ]
