# Generated by Django 5.0.4 on 2026-08-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='base_daily_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='مزد مبنا روزانه (روزانه + سنوات)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='محل تولد'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='citizenship_country_code',
            field=models.CharField(default='103', max_length=10, verbose_name='کشور تابعیت (۱۰۳=ایران)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='contract_base_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='حقوق قرارداد شده ماهانه (ریال)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='contract_hours',
            field=models.DecimalField(decimal_places=2, default=230, max_digits=8, verbose_name='ساعت کار قرارداد شده ماهانه'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='employment_type',
            field=models.CharField(default='2', max_length=20, verbose_name='نوع استخدام'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='exemption_type',
            field=models.CharField(default='1', max_length=20, verbose_name='نوع معافیت مالیاتی'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='gender',
            field=models.CharField(default='مرد', max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='group_status',
            field=models.CharField(default='شاغل', max_length=50, verbose_name='گروه (شاغل/بازنشسته)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='id_serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سریال شناسنامه'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='id_series',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مسلسل شناسنامه'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='include_in_bank',
            field=models.BooleanField(default=True, verbose_name='ارسال در فایل واریز بانک'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='include_in_insurance',
            field=models.BooleanField(default=True, verbose_name='ارسال در لیست دیسکت بیمه'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='include_in_tax',
            field=models.BooleanField(default=True, verbose_name='ارسال در فایل مالیات حقوق'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='insurance_name',
            field=models.CharField(default='تامین اجتماعی', max_length=100, verbose_name='نام بیمه'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='insurance_type',
            field=models.CharField(default='2', max_length=20, verbose_name='نوع بیمه'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='issue_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ صدور شناسنامه'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='issue_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='محل صدور'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='job_category',
            field=models.CharField(default='15', max_length=20, verbose_name='رسته شغلی'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='job_grade',
            field=models.CharField(default='19', max_length=20, verbose_name='گروه شغلی'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='nationality_code',
            field=models.CharField(default='1', max_length=10, verbose_name='کد ملیت (۱=ایران)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='personnel_id_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد/ردیف پرسنلی'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='residence_country_code',
            field=models.CharField(default='103', max_length=10, verbose_name='کشور محل زندگی (۱۰۳=ایران)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='retirement_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ بازنشستگی (شمسی)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='status_category',
            field=models.CharField(default='نفرات شرکتی', max_length=50, verbose_name='وضعیت (شرکتی/پیمانکاری)'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='ownership_type',
            field=models.CharField(choices=[('contract', 'استیجاری / پیمانکاری سرویسی'), ('company', 'خودرو شرکتی'), ('personal', 'خودرو ملکی راننده')], default='contract', max_length=20, verbose_name='نوع مالکیت'),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='base_years_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد سال کارکرد'),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='education_level',
            field=models.CharField(default='5', max_length=50, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره بیمه تامین اجتماعی'),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='job_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ۶ رقمی شغل بیمه'),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='job_title',
            field=models.CharField(max_length=150, verbose_name='سمت شغل / عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='marital_status',
            field=models.CharField(choices=[('single', 'مجرد'), ('married', 'متاهل')], default='single', max_length=20, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='national_code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='کد ملی (۱۰ رقم)'),
        ),
    ]
