# Generated by Django 5.0.4 on 2026-09-16 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_counterparty_account_code_accountingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinvoice',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='personnel.counterparty', verbose_name='طرف\u200cحساب'),
        ),
        migrations.AlterField(
            model_name='expenseinvoice',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='personnel.projectsection', verbose_name='بخش پروژه'),
        ),
        migrations.AlterField(
            model_name='payrollyearlysettings',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_yearly_settings', to='personnel.financialproject', verbose_name='پروژه مالی/عملیاتی (خالی=سراسری سازمان)'),
        ),
    ]
