# Generated by Django 5.0.4 on 2026-09-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_expenseinvoice_counterparty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty',
            name='section',
        ),
    ]
