# Generated by Django 5.0.4 on 2026-08-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_payrollyearlysettings_monthlypayrollrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='has_multiple_employers',
            field=models.BooleanField(default=False, verbose_name='بیش از یک کارفرما در ماه'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='is_tax_imported',
            field=models.BooleanField(default=False, verbose_name='مالیات از اکسل دارایی بارگذاری شده'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='tax_exemption_months',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد ماه اعمال شده در معافیت مالیاتی'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='tax_source_type',
            field=models.CharField(choices=[('MANUAL', 'دستی / پیش\u200cفرض سیستم'), ('IMPORTED_EXCEL', 'فایل اکسل دارایی'), ('CALCULATED_BRACKET', 'جدول مالیاتی ماده ۸۴')], default='MANUAL', max_length=50, verbose_name='منبع مالیات'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='surplus_overtime_percent',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='درصد تخصیص مازاد به اضافه\u200cکار (پیش\u200cفرض ۵۰٪)'),
        ),
    ]
