# Generated by Django 5.0.4 on 2026-09-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_remove_counterparty_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollyearlysettings',
            options={'ordering': ['-effective_from', 'project'], 'verbose_name': 'تنظیمات دوره\u200cای حقوق و دستمزد', 'verbose_name_plural': 'تنظیمات دوره\u200cای حقوق و دستمزد'},
        ),
        migrations.RemoveConstraint(
            model_name='payrollyearlysettings',
            name='unique_global_fiscal_year_setting',
        ),
        migrations.RemoveConstraint(
            model_name='payrollyearlysettings',
            name='unique_project_fiscal_year_setting',
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='effective_from',
            field=models.CharField(db_index=True, default='1405/01', max_length=7, verbose_name='ماه شروع اعتبار (مثال ۱۴۰۵/۰۱)'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='effective_to',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True, verbose_name='ماه پایان اعتبار (خالی=جاری)'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='version_title',
            field=models.CharField(default='احکام مصوب فروردین', max_length=150, verbose_name='عنوان نسخه احکام'),
        ),
        migrations.AddConstraint(
            model_name='payrollyearlysettings',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('fiscal_year', 'effective_from'), name='unique_global_effective_period_setting'),
        ),
        migrations.AddConstraint(
            model_name='payrollyearlysettings',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'fiscal_year', 'effective_from'), name='unique_project_effective_period_setting'),
        ),
    ]
