# Generated by Django 5.0.4 on 2026-08-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_monthlypayrollrecord_has_multiple_employers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='tax_currency_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='نرخ تسعیر ارز'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='tax_currency_type',
            field=models.CharField(default='84', max_length=10, verbose_name='نوع ارز مالیات (۸۴=ریال)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='tax_exceptions',
            field=models.CharField(default='1', max_length=10, verbose_name='استثنائات مالیات (۱=عادی / ۲=هیئت علمی / ۳=قضات / ۴=نفت و سکوها / ۵=پزشکان)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='tax_housing_benefit_type',
            field=models.CharField(default='1', max_length=10, verbose_name='مزایای مسکن مالیات (۱=عدم استفاده / ۲=با اثاثیه / ۳=بدون اثاثیه)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='tax_payment_type',
            field=models.CharField(default='1', max_length=10, verbose_name='نوع پرداختی مالیات (۱=ریالی / ۲=ارزی / ۳=ریالی ارزی)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='tax_service_location',
            field=models.CharField(default='1', max_length=10, verbose_name='محل خدمت مالیات (۱=عادی / ۲=مناطق محروم / ۳=دانش\u200cبنیان / ۴=ماده ۱۲)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='tax_vehicle_benefit_type',
            field=models.CharField(default='1', max_length=10, verbose_name='مزایای اتومبیل مالیات (۱=عدم استفاده / ۲=با راننده / ۳=بدون راننده)'),
        ),
    ]
