# Generated by Django 5.0.4 on 2026-08-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_personnelprofile_tax_currency_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='attendance_edit_future_days',
            field=models.IntegerField(default=0, verbose_name='حداکثر روزهای آینده مجاز برای ثبت کارکرد'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='attendance_edit_past_days',
            field=models.IntegerField(default=3, verbose_name='حداکثر روزهای گذشته مجاز برای ویرایش کارکرد'),
        ),
    ]
