# Generated by Django 5.0.4 on 2026-09-18 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_alter_payrollyearlysettings_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankexportsettings',
            name='source_sheba_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شبا مبدا (IR)'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='bonus_daily_coefficient',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='ضریب روزانه عیدی و پاداش'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_settings', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='friday_work_rate_multiplier',
            field=models.DecimalField(decimal_places=2, default=0.4, max_digits=4, verbose_name='ضریب نرخ جمعه\u200cکاری'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='max_insurable_daily_wage',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='سقف دستی دستمزد روزانه مشمول بیمه (خالی = ۷ برابر گروه ۱)'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='overtime_rate_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=4, verbose_name='ضریب نرخ اضافه\u200cکار'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='seniority_monthly_coefficient',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=6, verbose_name='ضریب ماهانه سنوات'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='standard_daily_hours',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='ساعت کار استاندارد روزانه'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payroll_settings', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده'),
        ),
    ]
