# Generated by Django 5.0.4 on 2026-09-18 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_bankexportsettings_source_sheba_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceiling_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='سقف مصوب تنخواه (ریال)')),
                ('card_or_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره کارت یا حساب تنخواه\u200cدار')),
                ('sheba_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شبا تنخواه\u200cدار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات / یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_accounts', to=settings.AUTH_USER_MODEL, verbose_name='تنخواه\u200cدار (کارمند)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_accounts', to='personnel.projectsection', verbose_name='بخش پروژه')),
            ],
            options={
                'verbose_name': 'حساب تنخواه\u200cگردان',
                'verbose_name_plural': 'حساب\u200cهای تنخواه\u200cگردان',
                'ordering': ['section', 'custodian'],
                'unique_together': {('section', 'custodian')},
            },
        ),
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', 'هزینه\u200cکرد از محل تنخواه (ارائه فاکتور/رسید)'), ('allocation', 'شارژ تنخواه (دریافت وجه از خزانه\u200cداری)'), ('refund', 'عودت مانده تنخواه به صندوق شرکت')], default='expense', max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ تراکنش (ریال)')),
                ('transaction_date_shamsi', models.CharField(max_length=10, verbose_name='تاریخ تراکنش (شمسی)')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان / شرح مختصر')),
                ('category', models.CharField(default='متفرقه', max_length=100, verbose_name='سرفصل هزینه / منبع شارژ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='شرح تفصیلی')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره رسید / فاکتور یا پیگیری بانکی')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='petty_cash/', verbose_name='تصویر فاکتور / رسید پرداخت')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس تنخواه\u200cدار'), ('pending_supervisor', 'در انتظار تایید سرپرست'), ('pending_accountant', 'در انتظار بررسی حسابدار'), ('approved', 'تایید نهایی / تسویه قطعی'), ('rejected', 'رد شده')], default='draft', max_length=30, verbose_name='وضعیت')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='علت رد درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='personnel.pettycashaccount', verbose_name='حساب تنخواه')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_transactions', to='personnel.counterparty', verbose_name='طرف\u200cحساب / فروشنده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_petty_cash_txs', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_transactions', to=settings.AUTH_USER_MODEL, verbose_name='تنخواه\u200cدار')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_transactions', to='personnel.projectsection', verbose_name='بخش پروژه')),
            ],
            options={
                'verbose_name': 'تراکنش تنخواه\u200cگردان',
                'verbose_name_plural': 'تراکنش\u200cهای تنخواه\u200cگردان',
                'ordering': ['-transaction_date_shamsi', '-created_at'],
                'indexes': [models.Index(fields=['section', 'custodian', 'transaction_date_shamsi'], name='personnel_p_section_d002e2_idx'), models.Index(fields=['status', 'transaction_type'], name='personnel_p_status_961b79_idx')],
            },
        ),
    ]
