# Generated by Django 5.0.4 on 2026-08-28 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_payrollyearlysettings_attendance_edit_future_days_and_more'),
        ('warehouses', '0003_add_label_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendances', to='warehouses.warehouse', verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='monthlyworkperiod',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_periods', to='warehouses.warehouse', verbose_name='انبار مربوطه'),
        ),
    ]
