# Generated by Django 5.0.4 on 2026-09-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_pettycashaccount_pettycashtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='personnel_docs/', verbose_name='تصویر یا فایل مدارک پرسنل (کارت ملی / شناسنامه)'),
        ),
    ]
