# Generated by Django 5.0.4 on 2026-08-29 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_alter_dailyattendance_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت رد توسط حسابداری'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='submission_notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت سرپرست هنگام ارسال'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال جهت بررسی'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_work_periods', to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکننده جهت بررسی'),
        ),
        migrations.AlterField(
            model_name='monthlyworkperiod',
            name='status',
            field=models.CharField(choices=[('OPEN', 'باز (امکان ثبت و ویرایش)'), ('SUBMITTED', 'ارسال\u200cشده جهت بررسی مالی'), ('LOCKED', 'تایید نهایی و قفل\u200cشده'), ('REJECTED', 'رد شده و نیازمند بازبینی'), ('FINALIZED', 'قطعی و تسویه\u200cشده')], default='OPEN', max_length=15, verbose_name='وضعیت دوره'),
        ),
    ]
