# Generated by Django 5.0.4 on 2026-09-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_personnelprofile_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelprofile',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس کارمند انبار'), ('pending_supervisor', 'در انتظار تایید سرپرست انبار'), ('supervisor_approved', 'تایید سرپرست / در انتظار حسابدار'), ('pending_accountant', 'در انتظار بررسی حسابدار'), ('accountant_approved', 'تایید حسابدار / در انتظار مدیر'), ('pending_manager', 'در انتظار تایید مدیر'), ('manager_approved', 'تایید مدیر / در انتظار حسابدار'), ('approved', 'تصویب و فعال شده'), ('ready_to_pay', 'تایید مدیر / آماده پرداخت خزانه\u200cداری'), ('paid', 'پرداخت و تسویه نهایی شده'), ('revision_required', 'نیازمند بازنگری و اصلاح'), ('rejected', 'رد شده / ابطال')], db_index=True, default='draft', max_length=30, verbose_name='وضعیت تایید'),
        ),
        migrations.AlterField(
            model_name='vehicledriverprofile',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس کارمند انبار'), ('pending_supervisor', 'در انتظار تایید سرپرست انبار'), ('supervisor_approved', 'تایید سرپرست / در انتظار حسابدار'), ('pending_accountant', 'در انتظار بررسی حسابدار'), ('accountant_approved', 'تایید حسابدار / در انتظار مدیر'), ('pending_manager', 'در انتظار تایید مدیر'), ('manager_approved', 'تایید مدیر / در انتظار حسابدار'), ('approved', 'تصویب و فعال شده'), ('ready_to_pay', 'تایید مدیر / آماده پرداخت خزانه\u200cداری'), ('paid', 'پرداخت و تسویه نهایی شده'), ('revision_required', 'نیازمند بازنگری و اصلاح'), ('rejected', 'رد شده / ابطال')], db_index=True, default='draft', max_length=30, verbose_name='وضعیت تایید'),
        ),
    ]
