# Generated by Django 5.0.4 on 2026-08-30 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_monthlyworkperiod_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTripAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=150, verbose_name='نام راننده')),
                ('plate_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='پلاک')),
                ('date_shamsi', models.CharField(max_length=10, verbose_name='تاریخ کارکرد')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تغییر')),
                ('field_name', models.CharField(max_length=100, verbose_name='نام فیلد')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='مقدار قبلی')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='مقدار جدید')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='دلیل ویرایش')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویرایش\u200cکننده')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='personnel.vehicletriplog', verbose_name='رکورد سرویس ناوگان')),
            ],
            options={
                'verbose_name': 'لاگ ممیزی ناوگان',
                'verbose_name_plural': 'لاگ\u200cهای ممیزی ناوگان',
                'ordering': ['-changed_at'],
            },
        ),
    ]
