# Generated by Django 5.0.4 on 2026-09-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_alter_personnelprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='is_driver_owner',
            field=models.BooleanField(default=True, verbose_name='مالک شخص راننده است'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='owner_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام و نام خانوادگی مالک'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='owner_national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی مالک'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس مالک'),
        ),
    ]
