# Generated by Django 5.0.4 on 2026-08-30 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_vehicletripauditlog'),
        ('warehouses', '0003_add_label_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletriplog',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_trip_logs', to='warehouses.warehouse', verbose_name='انبار'),
        ),
    ]
