# Generated by Django 5.0.4 on 2026-09-23 08:20

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_vehicledriverprofile_is_driver_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledriverprofile',
            name='default_service_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نرخ پایه پیش\u200cفرض به ازای هر سرویس (ریال)'),
        ),
        migrations.AlterField(
            model_name='vehicledriverprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('pickup', 'وانت'), ('nissan', 'نیسان'), ('khavar', 'خاور'), ('sedan', 'سواری'), ('truck', 'کامیون تک/جفت'), ('trailer', 'تریلی'), ('forklift', 'لیفتراک'), ('other', 'سایر')], default='nissan', max_length=20, verbose_name='نوع خودرو'),
        ),
        migrations.AddConstraint(
            model_name='vehicledriverprofile',
            constraint=models.CheckConstraint(check=models.Q(('default_service_rate__gte', 0)), name='vehicle_default_rate_gte_0'),
        ),
    ]
