# Generated by Django 5.0.4 on 2026-08-31 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_alter_vehicletriplog_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='accountant_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت تایید حسابدار'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='accountant_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_approved_personnel', to=settings.AUTH_USER_MODEL, verbose_name='حسابدار تاییدکننده'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس / در انتظار تایید مدیر'), ('manager_approved', 'تایید مدیر / در انتظار حسابدار'), ('approved', 'تایید نهایی شده'), ('revision_required', 'نیازمند بازنگری و اصلاح'), ('rejected', 'رد شده')], db_index=True, default='approved', max_length=20, verbose_name='وضعیت تایید'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='has_pending_changes',
            field=models.BooleanField(default=False, verbose_name='دارای درخواست تغییرات معلق'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت تایید مدیر'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_personnel', to=settings.AUTH_USER_MODEL, verbose_name='مدیر تاییدکننده'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل رد یا بازنگری'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='accountant_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت تایید حسابدار'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='accountant_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_approved_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='حسابدار تاییدکننده'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس / در انتظار تایید مدیر'), ('manager_approved', 'تایید مدیر / در انتظار حسابدار'), ('approved', 'تایید نهایی شده'), ('revision_required', 'نیازمند بازنگری و اصلاح'), ('rejected', 'رد شده')], db_index=True, default='approved', max_length=20, verbose_name='وضعیت تایید'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='has_pending_changes',
            field=models.BooleanField(default=False, verbose_name='دارای درخواست تغییرات معلق'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت تایید مدیر'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='مدیر تاییدکننده'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل رد یا بازنگری'),
        ),
        migrations.CreateModel(
            name='PersonnelChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_changes', models.JSONField(default=dict, verbose_name='فیلدهای تغییریافته (داده\u200cهای جدید)')),
                ('previous_values', models.JSONField(blank=True, default=dict, verbose_name='مقادیر پیشین (جهت مقایسه)')),
                ('status', models.CharField(choices=[('pending_manager', 'در انتظار بررسی مدیر'), ('manager_approved', 'تایید مدیر / در انتظار حسابدار'), ('approved', 'تایید نهایی و اعمال شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending_manager', max_length=20, verbose_name='وضعیت درخواست')),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی مدیر')),
                ('accountant_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی حسابدار')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='توضیحات و دلیل رد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('accountant_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_acc_personnel_changes', to=settings.AUTH_USER_MODEL, verbose_name='حسابدار بررسی\u200cکننده')),
                ('manager_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mgr_personnel_changes', to=settings.AUTH_USER_MODEL, verbose_name='مدیر بررسی\u200cکننده')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='personnel.personnelprofile', verbose_name='پرسنل هدف')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده')),
            ],
            options={
                'verbose_name': 'درخواست تغییرات پرسنل',
                'verbose_name_plural': 'درخواست\u200cهای تغییرات پرسنل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_changes', models.JSONField(default=dict, verbose_name='فیلدهای تغییریافته (داده\u200cهای جدید)')),
                ('previous_values', models.JSONField(blank=True, default=dict, verbose_name='مقادیر پیشین (جهت مقایسه)')),
                ('status', models.CharField(choices=[('pending_manager', 'در انتظار بررسی مدیر'), ('manager_approved', 'تایید مدیر / در انتظار حسابدار'), ('approved', 'تایید نهایی و اعمال شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending_manager', max_length=20, verbose_name='وضعیت درخواست')),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی مدیر')),
                ('accountant_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی حسابدار')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='توضیحات و دلیل رد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('accountant_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_acc_vehicle_changes', to=settings.AUTH_USER_MODEL, verbose_name='حسابدار بررسی\u200cکننده')),
                ('manager_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mgr_vehicle_changes', to=settings.AUTH_USER_MODEL, verbose_name='مدیر بررسی\u200cکننده')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='personnel.vehicledriverprofile', verbose_name='خودرو/راننده هدف')),
            ],
            options={
                'verbose_name': 'درخواست تغییرات خودرو',
                'verbose_name_plural': 'درخواست\u200cهای تغییرات خودروها',
                'ordering': ['-created_at'],
            },
        ),
    ]
