# Generated by Django 5.0.4 on 2026-09-23 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_alter_vehicledriverprofile_default_service_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد یکتای شرکت')),
                ('name', models.CharField(max_length=200, verbose_name='نام کامل شرکت')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی ۱۱ رقمی')),
                ('economic_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد اقتصادی')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره ثبت')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تلفن')),
                ('address', models.TextField(blank=True, null=True, verbose_name='نشانی دفتر مرکزی')),
                ('ceo_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام مدیرعامل')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='لوگوی شرکت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='payrollyearlysettings',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_yearly_settings', to='personnel.financialproject', verbose_name='پروژه مالی/عملیاتی (خالی=سراسری شرکت)'),
        ),
        migrations.AddField(
            model_name='financialproject',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='personnel.company', verbose_name='شرکت متبوع'),
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_yearly_settings', to='personnel.company', verbose_name='شرکت متبوع'),
        ),
        migrations.CreateModel(
            name='UserCompanyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='شرکت پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='personnel.company', verbose_name='شرکت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_accesses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی کاربر به شرکت',
                'verbose_name_plural': 'دسترسی\u200cهای کاربران به شرکت\u200cها',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
