# Generated by Django 5.0.4 on 2026-08-31 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_personnelprofile_accountant_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت خزانه\u200cداری'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='خزانه\u200cدار پرداخت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='payment_batch_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه دسته واریز پایا'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='payment_failure_reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت عدم واریز یا خطای شبا'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'در انتظار تایید'), ('READY_TO_PAY', 'تایید مدیر / آماده پرداخت'), ('PAID', 'پرداخت و تسویه شده'), ('FAILED_SHEBA', 'خطای شماره شبا / حساب بانکی'), ('REJECTED', 'رد شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت پرداخت خزانه\u200cداری'),
        ),
        migrations.AddField(
            model_name='monthlypayrollrecord',
            name='payment_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری بانکی واریز'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='accountant_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید حسابدار'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='accountant_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_approved_work_periods', to=settings.AUTH_USER_MODEL, verbose_name='حسابدار تاییدکننده'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید مدیر'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mgr_approved_work_periods', to=settings.AUTH_USER_MODEL, verbose_name='مدیر تاییدکننده'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='payment_batch_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه دسته پرداخت پایا'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='payment_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری بانکی تسویه'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بازنگری'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='revision_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_req_work_periods', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده بازنگری'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='supervisor_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید سرپرست'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='supervisor_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sup_approved_work_periods', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست تاییدکننده'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='treasury_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت خزانه\u200cدار'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='treasury_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_paid_work_periods', to=settings.AUTH_USER_MODEL, verbose_name='خزانه\u200cدار تسویه\u200cکننده'),
        ),
        migrations.AddField(
            model_name='personnelchangerequest',
            name='auto_passed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان عبور هوشمند'),
        ),
        migrations.AddField(
            model_name='personnelchangerequest',
            name='auto_passed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopassed_p_changes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر عبور هوشمند'),
        ),
        migrations.AddField(
            model_name='personnelchangerequest',
            name='is_auto_passed',
            field=models.BooleanField(default=False, verbose_name='اعمال شده با عبور هوشمند'),
        ),
        migrations.AddField(
            model_name='personnelchangerequest',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان درخواست بازنگری'),
        ),
        migrations.AddField(
            model_name='personnelchangerequest',
            name='revision_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_req_p_changes', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده بازنگری'),
        ),
        migrations.AddField(
            model_name='personnelchangerequest',
            name='supervisor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی سرپرست'),
        ),
        migrations.AddField(
            model_name='personnelchangerequest',
            name='supervisor_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sup_personnel_changes', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست بررسی\u200cکننده'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='auto_passed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان عبور هوشمند'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='auto_passed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopassed_personnel', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده عبور هوشمند'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='is_auto_passed',
            field=models.BooleanField(default=False, verbose_name='تایید شده با اصل عبور هوشمند'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='payment_method',
            field=models.CharField(blank=True, default='PAYA', max_length=50, null=True, verbose_name='روش پرداخت (پایا / ساتنا / کارت / چک / نقدی)'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='payment_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری / کد رهگیری بانکی'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان درخواست بازنگری'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='revision_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_req_personnel', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده بازنگری'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='supervisor_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت تایید سرپرست'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='supervisor_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_approved_personnel', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست تاییدکننده'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='treasury_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت پرداخت خزانه\u200cدار'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='treasury_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_paid_personnel', to=settings.AUTH_USER_MODEL, verbose_name='خزانه\u200cدار پرداخت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='vehiclechangerequest',
            name='auto_passed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان عبور هوشمند'),
        ),
        migrations.AddField(
            model_name='vehiclechangerequest',
            name='auto_passed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopassed_v_changes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر عبور هوشمند'),
        ),
        migrations.AddField(
            model_name='vehiclechangerequest',
            name='is_auto_passed',
            field=models.BooleanField(default=False, verbose_name='اعمال شده با عبور هوشمند'),
        ),
        migrations.AddField(
            model_name='vehiclechangerequest',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان درخواست بازنگری'),
        ),
        migrations.AddField(
            model_name='vehiclechangerequest',
            name='revision_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_req_v_changes', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده بازنگری'),
        ),
        migrations.AddField(
            model_name='vehiclechangerequest',
            name='supervisor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی سرپرست'),
        ),
        migrations.AddField(
            model_name='vehiclechangerequest',
            name='supervisor_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sup_vehicle_changes', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست بررسی\u200cکننده'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='auto_passed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان عبور هوشمند'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='auto_passed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopassed_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده عبور هوشمند'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='is_auto_passed',
            field=models.BooleanField(default=False, verbose_name='تایید شده با اصل عبور هوشمند'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='payment_method',
            field=models.CharField(blank=True, default='PAYA', max_length=50, null=True, verbose_name='روش پرداخت (پایا / ساتنا / کارت / چک / نقدی)'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='payment_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری / کد رهگیری بانکی'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان درخواست بازنگری'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='revision_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_req_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده بازنگری'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='supervisor_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت تایید سرپرست'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='supervisor_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_approved_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست تاییدکننده'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='treasury_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت پرداخت خزانه\u200cدار'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='treasury_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_paid_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='خزانه\u200cدار پرداخت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='vehicletriplog',
            name='is_settled',
            field=models.BooleanField(default=False, verbose_name='تسویه شده'),
        ),
        migrations.AddField(
            model_name='vehicletriplog',
            name='payment_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری پرداخت بانکی'),
        ),
        migrations.AddField(
            model_name='vehicletriplog',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تسویه'),
        ),
        migrations.AddField(
            model_name='vehicletriplog',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_trips', to=settings.AUTH_USER_MODEL, verbose_name='کاربر تسویه\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='monthlyworkperiod',
            name='status',
            field=models.CharField(choices=[('OPEN', 'باز (امکان ثبت و ویرایش)'), ('SUBMITTED_SUPERVISOR', 'تایید و ارسال سرپرست انبار'), ('SUBMITTED_ACCOUNTANT', 'تایید و ارسال حسابدار'), ('READY_TO_PAY', 'تایید مدیر / آماده پرداخت خزانه\u200cداری'), ('PAID', 'پرداخت و تسویه قطعی خزانه\u200cداری'), ('SUBMITTED', 'ارسال\u200cشده جهت بررسی مالی'), ('LOCKED', 'تایید نهایی و قفل\u200cشده'), ('FINALIZED', 'قطعی و تسویه\u200cشده'), ('REVISION_REQUIRED', 'نیازمند بازنگری و اصلاح'), ('REJECTED', 'رد شده و نیازمند بازبینی')], default='OPEN', max_length=25, verbose_name='وضعیت دوره'),
        ),
        migrations.AlterField(
            model_name='personnelchangerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس کارمند انبار'), ('pending_supervisor', 'در انتظار بررسی سرپرست انبار'), ('supervisor_approved', 'تایید سرپرست / در انتظار حسابدار'), ('pending_accountant', 'در انتظار بررسی حسابدار'), ('accountant_approved', 'تایید حسابدار / در انتظار مدیر'), ('pending_manager', 'در انتظار بررسی مدیر'), ('manager_approved', 'تایید مدیر / در انتظار حسابدار'), ('approved', 'تایید نهایی و اعمال شده'), ('revision_required', 'نیازمند بازنگری و اصلاح'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending_manager', max_length=30, verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس کارمند انبار'), ('pending_supervisor', 'در انتظار تایید سرپرست انبار'), ('supervisor_approved', 'تایید سرپرست / در انتظار حسابدار'), ('pending_accountant', 'در انتظار بررسی حسابدار'), ('accountant_approved', 'تایید حسابدار / در انتظار مدیر'), ('pending_manager', 'در انتظار تایید مدیر'), ('manager_approved', 'تایید مدیر / در انتظار حسابدار'), ('approved', 'تصویب و فعال شده'), ('ready_to_pay', 'تایید مدیر / آماده پرداخت خزانه\u200cداری'), ('paid', 'پرداخت و تسویه نهایی شده'), ('revision_required', 'نیازمند بازنگری و اصلاح'), ('rejected', 'رد شده / ابطال')], db_index=True, default='approved', max_length=30, verbose_name='وضعیت تایید'),
        ),
        migrations.AlterField(
            model_name='vehiclechangerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس کارمند انبار'), ('pending_supervisor', 'در انتظار بررسی سرپرست انبار'), ('supervisor_approved', 'تایید سرپرست / در انتظار حسابدار'), ('pending_accountant', 'در انتظار بررسی حسابدار'), ('accountant_approved', 'تایید حسابدار / در انتظار مدیر'), ('pending_manager', 'در انتظار بررسی مدیر'), ('manager_approved', 'تایید مدیر / در انتظار حسابدار'), ('approved', 'تایید نهایی و اعمال شده'), ('revision_required', 'نیازمند بازنگری و اصلاح'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending_manager', max_length=30, verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterField(
            model_name='vehicledriverprofile',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس کارمند انبار'), ('pending_supervisor', 'در انتظار تایید سرپرست انبار'), ('supervisor_approved', 'تایید سرپرست / در انتظار حسابدار'), ('pending_accountant', 'در انتظار بررسی حسابدار'), ('accountant_approved', 'تایید حسابدار / در انتظار مدیر'), ('pending_manager', 'در انتظار تایید مدیر'), ('manager_approved', 'تایید مدیر / در انتظار حسابدار'), ('approved', 'تصویب و فعال شده'), ('ready_to_pay', 'تایید مدیر / آماده پرداخت خزانه\u200cداری'), ('paid', 'پرداخت و تسویه نهایی شده'), ('revision_required', 'نیازمند بازنگری و اصلاح'), ('rejected', 'رد شده / ابطال')], db_index=True, default='approved', max_length=30, verbose_name='وضعیت تایید'),
        ),
    ]
