# Generated by Django 5.0.4 on 2026-09-03 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_monthlypayrollrecord_paid_at_and_more'),
        ('warehouses', '0003_add_label_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شخص یا شرکت')),
                ('counterparty_type', models.CharField(choices=[('driver', 'راننده / مالک خودرو'), ('repair_shop', 'تعمیرگاه و قطعات'), ('fuel_station', 'جایگاه سوخت'), ('contractor', 'پیمانکار خدماتی'), ('other', 'سایر اشخاص حقیقی/حقوقی')], default='other', max_length=30, verbose_name='نوع طرف\u200cحساب')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی / شناسه اقتصادی')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن تماس')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بانک')),
                ('sheba_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شبا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طرف\u200cحساب مالی',
                'verbose_name_plural': 'طرف\u200cحساب\u200cهای مالی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد پروژه')),
                ('name', models.CharField(max_length=200, verbose_name='نام پروژه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پروژه مالی/عملیاتی',
                'verbose_name_plural': 'پروژه\u200cهای مالی/عملیاتی',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserSectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'کارمند / اپراتور ثبت'), ('supervisor', 'سرپرست بخش'), ('accountant', 'حسابدار پروژه'), ('manager', 'مدیر پروژه'), ('treasury', 'خزانه\u200cدار کل')], default='employee', max_length=30, verbose_name='نقش در بخش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'انتساب کاربر به بخش',
                'verbose_name_plural': 'انتساب\u200cهای کاربران به بخش\u200cها',
            },
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendances', to='personnel.financialproject', verbose_name='پروژه مالی/عملیاتی'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_profiles', to='personnel.financialproject', verbose_name='پروژه مالی/عملیاتی'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='personnel.financialproject', verbose_name='پروژه مالی/عملیاتی'),
        ),
        migrations.AddField(
            model_name='vehicletriplog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_trip_logs', to='personnel.financialproject', verbose_name='پروژه مالی/عملیاتی'),
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='کد بخش')),
                ('name', models.CharField(max_length=200, verbose_name='نام بخش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='personnel.financialproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'بخش پروژه',
                'verbose_name_plural': 'بخش\u200cهای پروژه',
                'ordering': ['project', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='شماره فاکتور / رسید')),
                ('invoice_date_shamsi', models.CharField(max_length=10, verbose_name='تاریخ فاکتور (شمسی)')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ فاکتور (ریال)')),
                ('category', models.CharField(max_length=100, verbose_name='سرفصل هزینه')),
                ('description', models.TextField(verbose_name='شرح هزینه')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='تصویر یا فایل فاکتور')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس کارمند'), ('pending_supervisor', 'در انتظار تایید سرپرست'), ('pending_accountant', 'در انتظار بررسی حسابدار'), ('ready_to_pay', 'تایید مدیر / آماده پرداخت'), ('paid', 'پرداخت\u200cشده توسط خزانه\u200cدار'), ('rejected', 'رد شده')], default='draft', max_length=30, verbose_name='وضعیت فاکتور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='personnel.counterparty', verbose_name='طرف\u200cحساب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده فاکتور')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='personnel.projectsection', verbose_name='بخش پروژه')),
            ],
            options={
                'verbose_name': 'فاکتور هزینه',
                'verbose_name_plural': 'فاکتورهای هزینه',
                'ordering': ['-invoice_date_shamsi', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='counterparty',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='personnel.projectsection', verbose_name='بخش منتسب'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendances', to='personnel.projectsection', verbose_name='بخش/دپارتمان پروژه'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_profiles', to='personnel.projectsection', verbose_name='بخش/دپارتمان پروژه'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='personnel.projectsection', verbose_name='بخش/دپارتمان پروژه'),
        ),
        migrations.AddField(
            model_name='vehicletriplog',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_trip_logs', to='personnel.projectsection', verbose_name='بخش/دپارتمان پروژه'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['section', 'date_shamsi'], name='personnel_d_section_2c4afc_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletriplog',
            index=models.Index(fields=['section', 'date_shamsi'], name='personnel_v_section_0a1e2c_idx'),
        ),
        migrations.AddField(
            model_name='usersectionassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='personnel.projectsection', verbose_name='بخش پروژه'),
        ),
        migrations.AddField(
            model_name='usersectionassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سیستم'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsection',
            unique_together={('project', 'code')},
        ),
        migrations.AddIndex(
            model_name='expenseinvoice',
            index=models.Index(fields=['section', 'invoice_date_shamsi'], name='personnel_e_section_21e447_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseinvoice',
            index=models.Index(fields=['counterparty', 'invoice_number'], name='personnel_e_counter_73503f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersectionassignment',
            unique_together={('user', 'section', 'role')},
        ),
    ]
