# Generated by Django 5.0.4 on 2026-09-03 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_counterparty_financialproject_usersectionassignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollyearlysettings',
            options={'ordering': ['-fiscal_year', 'project'], 'verbose_name': 'تنظیمات سالانه حقوق و دستمزد', 'verbose_name_plural': 'تنظیمات سالانه حقوق و دستمزد'},
        ),
        migrations.AddField(
            model_name='payrollyearlysettings',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_yearly_settings', to='personnel.financialproject', verbose_name='پروژه مالی/عملیاتی (خالی=سراسری سازمان)'),
        ),
        migrations.AlterField(
            model_name='payrollyearlysettings',
            name='fiscal_year',
            field=models.CharField(db_index=True, max_length=4, verbose_name='سال مالی (مثال ۱۴۰۵)'),
        ),
        migrations.AddConstraint(
            model_name='payrollyearlysettings',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('fiscal_year',), name='unique_global_fiscal_year_setting'),
        ),
        migrations.AddConstraint(
            model_name='payrollyearlysettings',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('fiscal_year', 'project'), name='unique_project_fiscal_year_setting'),
        ),
    ]
