# Generated by Django 5.0.4 on 2026-09-24 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_seed_initial_companies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payrollyearlysettings',
            name='unique_global_effective_period_setting',
        ),
        migrations.AddConstraint(
            model_name='payrollyearlysettings',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True), ('project__isnull', True)), fields=('fiscal_year', 'effective_from'), name='unique_global_effective_period_setting'),
        ),
        migrations.AddConstraint(
            model_name='payrollyearlysettings',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False), ('project__isnull', True)), fields=('company', 'fiscal_year', 'effective_from'), name='unique_company_effective_period_setting'),
        ),
    ]
