# Generated by Django 5.0.4 on 2026-09-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_make_payroll_settings_project_scoped'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب'),
        ),
    ]
