# Generated by Django 5.0.4 on 2026-09-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_remove_payrollyearlysettings_unique_global_effective_period_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_warehouse_module',
            field=models.BooleanField(default=True, verbose_name='دسترسی به سامانه انبارداری و انبارگردانی'),
        ),
    ]
