# Generated by Django 5.0.4 on 2026-09-25 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0015_company_has_warehouse_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='alternate_inspector',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='بازرس علی\u200cالبدل'),
        ),
        migrations.AddField(
            model_name='company',
            name='articles_of_association',
            field=models.FileField(blank=True, null=True, upload_to='company_core_docs/', verbose_name='فایل اساسنامه'),
        ),
        migrations.AddField(
            model_name='company',
            name='authorized_signers',
            field=models.TextField(blank=True, null=True, verbose_name='صاحبان امضای مجاز و حدود اختیارات'),
        ),
        migrations.AddField(
            model_name='company',
            name='board_chairman',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='رئیس هیئت\u200cمدیره'),
        ),
        migrations.AddField(
            model_name='company',
            name='board_term_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای دوره تصدی هیئت\u200cمدیره'),
        ),
        migrations.AddField(
            model_name='company',
            name='board_vice_chairman',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نایب\u200cرئیس هیئت\u200cمدیره'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('private_joint_stock', 'سهامی خاص'), ('public_joint_stock', 'سهامی عام'), ('limited_liability', 'با مسئولیت محدود'), ('cooperative', 'تعاونی'), ('holding', 'هلدینگ / شرکت مادر'), ('other', 'سایر')], default='private_joint_stock', max_length=50, verbose_name='نوع شرکت'),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_row',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ردیف پیمان بیمه'),
        ),
        migrations.AddField(
            model_name='company',
            name='employer_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام کارفرما در لیست بیمه'),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_year_start_month',
            field=models.IntegerField(default=1, verbose_name='ماه شروع سال مالی (۱ تا ۱۲)'),
        ),
        migrations.AddField(
            model_name='company',
            name='latest_gazette',
            field=models.FileField(blank=True, null=True, upload_to='company_core_docs/', verbose_name='فایل آخرین روزنامه رسمی'),
        ),
        migrations.AddField(
            model_name='company',
            name='main_inspector',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='بازرس اصلی'),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی ۱۰ رقمی اقامتگاه قانونی'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب رسمی'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بانک اصلی'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='شماره شبا رسمی (IR...)'),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_capital',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='سرمایه ثبتی (ریال)'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AddField(
            model_name='company',
            name='share_nominal_value',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ارزش اسمی هر سهم (ریال)'),
        ),
        migrations.AddField(
            model_name='company',
            name='shares_count',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='تعداد سهام'),
        ),
        migrations.AddField(
            model_name='company',
            name='social_security_branch_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد شعبه تأمین اجتماعی'),
        ),
        migrations.AddField(
            model_name='company',
            name='social_security_branch_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شعبه تأمین اجتماعی'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_economic_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد اقتصادی جدید ۱۶ رقمی'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_memory_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه یکتای حافظه مالیاتی (۶ کاراکتر)'),
        ),
        migrations.AddField(
            model_name='company',
            name='workshop_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد کارگاه تأمین اجتماعی (۱۰ رقم)'),
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('statute', 'اساسنامه شرکت'), ('establishment_gazette', 'روزنامه رسمی تأسیس'), ('changes_gazette', 'روزنامه رسمی آخرین تغییرات هیئت\u200cمدیره'), ('auditors_gazette', 'روزنامه رسمی تمدید بازرسان'), ('capital_gazette', 'روزنامه رسمی تغییرات سرمایه و آدرس'), ('vat_certificate', 'گواهی ثبت\u200cنام ارزش افزوده'), ('tax_clearance', 'مفاصاحساب مالیاتی / بیمه\u200cای'), ('commercial_card', 'کارت بازرگانی'), ('contractor_qualification', 'گواهی رتبه\u200cبندی / صلاحیت پیمانکاری (ساجار)'), ('labor_safety_certificate', 'گواهی صلاحیت ایمنی پیمانکاران (اداره کار)'), ('operating_license', 'پروانه بهره\u200cبرداری / جواز فعالیت'), ('lease_contract', 'سند مالکیت / اجاره\u200cنامه رسمی'), ('master_agreement', 'قرارداد مادر یا تفاهم\u200cنامه'), ('other', 'سایر مدارک و اسناد رسمی')], default='other', max_length=50, verbose_name='نوع مدرک')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مدرک')),
                ('file', models.FileField(upload_to='company_documents/', verbose_name='فایل ضمیمه')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='اندازه فایل به بایت')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='سند محرمانه (صرفاً مدیران ارشد)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات و نکات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='personnel.company', verbose_name='شرکت متبوع')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر بارگذاری\u200cکننده')),
            ],
            options={
                'verbose_name': 'مدرک شرکت',
                'verbose_name_plural': 'مدارک و اسناد شرکت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
