# Generated by Django 5.0.4 on 2026-09-25 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0016_company_alternate_inspector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب')),
                ('sheba_number', models.CharField(max_length=34, verbose_name='شماره شبا (IR...)')),
                ('account_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان/کاربرد حساب (مثلاً: واریز حقوق، تنخواه، بازرگانی)')),
                ('is_primary', models.BooleanField(default=False, verbose_name='حساب اصلی / پیش\u200cفرض تسویه حقوق')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='personnel.company', verbose_name='شرکت متبوع')),
            ],
            options={
                'verbose_name': 'حساب بانکی شرکت',
                'verbose_name_plural': 'حساب\u200cهای بانکی شرکت\u200cها',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
