# Generated by Django 5.0.4 on 2026-09-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0017_companybankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompanyaccess',
            name='access_level',
            field=models.CharField(choices=[('docs_read', 'فقط مشاهده مدارک رسمی'), ('docs_write', 'مشاهده و بارگذاری مدارک رسمی'), ('workspace_full', 'عضویت کامل در فضای کاری و ماژول\u200cها')], default='docs_read', max_length=30, verbose_name='سطح دسترسی سازمانی'),
        ),
        migrations.AddField(
            model_name='usercompanyaccess',
            name='role_in_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سمت / نقش در این شرکت'),
        ),
    ]
