# Generated by Django 5.0.4 on 2026-09-26 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0018_usercompanyaccess_access_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='is_superseded',
            field=models.BooleanField(default=False, verbose_name='سند منسوخ / جایگزین شده با نسخه جدید'),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='version',
            field=models.IntegerField(default=1, verbose_name='شماره ویرایش / نسخه'),
        ),
        migrations.CreateModel(
            name='CompanyBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی (۱۰ رقم)')),
                ('member_type', models.CharField(choices=[('real', 'شخص حقیقی'), ('legal_rep', 'نماینده شخص حقوقی')], default='real', max_length=20, verbose_name='نوع عضو')),
                ('represented_legal_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام شخصیت حقوقی متبوع')),
                ('role', models.CharField(choices=[('chairman', 'رئیس هیئت\u200cمدیره'), ('vice_chairman', 'نایب\u200cرئیس هیئت\u200cمدیره'), ('board_member', 'عضو هیئت\u200cمدیره'), ('managing_director', 'مدیرعامل'), ('managing_director_and_member', 'عضو هیئت\u200cمدیره و مدیرعامل'), ('main_inspector', 'بازرس اصلی'), ('alternate_inspector', 'بازرس علی\u200cالبدل'), ('secretary', 'دبیر هیئت\u200cمدیره'), ('other', 'سایر ارکان قانونی')], default='board_member', max_length=40, verbose_name='سمت')),
                ('has_signature_right', models.BooleanField(default=False, verbose_name='دارای حق امضای تعهدآور')),
                ('signature_scope', models.CharField(blank=True, max_length=250, null=True, verbose_name='حدود اختیارات امضا')),
                ('term_start', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع تصدی')),
                ('term_expiry', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان تصدی (حداکثر ۲ سال)')),
                ('attached_id_doc', models.FileField(blank=True, null=True, upload_to='company_board_docs/', verbose_name='تصویر کارت ملی / شناسنامه')),
                ('attached_appointment_doc', models.FileField(blank=True, null=True, upload_to='company_board_docs/', verbose_name='حکم انتصاب / صورتجلسه مجمع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='personnel.company', verbose_name='شرکت متبوع')),
            ],
            options={
                'verbose_name': 'عضو هیئت\u200cمدیره شرکت',
                'verbose_name_plural': 'اعضای هیئت\u200cمدیره شرکت\u200cها',
                'ordering': ['-has_signature_right', 'role', '-created_at'],
            },
        ),
    ]
