# Generated by Django 5.0.4 on 2026-09-27 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0019_companydocument_is_superseded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='personnel.company', verbose_name='شرکت متبوع'),
        ),
        migrations.AddField(
            model_name='monthlyworkperiod',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_work_periods', to='personnel.company', verbose_name='شرکت متبوع'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnel_profiles', to='personnel.company', verbose_name='شرکت متبوع'),
        ),
        migrations.CreateModel(
            name='CompanyFiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(db_index=True, max_length=4, verbose_name='سال مالی (مثال ۱۴۰۵)')),
                ('title', models.CharField(default='سال مالی جاری', max_length=150, verbose_name='عنوان دوره')),
                ('start_date', models.CharField(max_length=10, verbose_name='تاریخ شروع دوره (شمسی)')),
                ('end_date', models.CharField(max_length=10, verbose_name='تاریخ پایان دوره (شمسی)')),
                ('status', models.CharField(choices=[('open', 'باز (امکان ثبت و ویرایش اسناد)'), ('frozen', 'منجمد / در حال رسیدگی و انبارگردانی'), ('closed', 'بسته شده / قطعی و غیرقابل ویرایش')], default='open', max_length=20, verbose_name='وضعیت دوره مالی')),
                ('is_active', models.BooleanField(default=True, verbose_name='دوره پیش\u200cفرض فعال')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بستن سال مالی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات و مصوبات مجمع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_periods', to=settings.AUTH_USER_MODEL, verbose_name='کاربر بسته\u200cکننده دوره')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='personnel.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'دوره مالی شرکت',
                'verbose_name_plural': 'دوره\u200cهای مالی شرکت\u200cها',
                'ordering': ['-fiscal_year'],
                'unique_together': {('company', 'fiscal_year')},
            },
        ),
    ]
