# Generated by Django 5.0.4 on 2026-09-27 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0020_counterparty_company_monthlyworkperiod_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlyworkperiod',
            name='unique_warehouse_year_month_period',
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='personnel.company', verbose_name='شرکت متبوع'),
        ),
        migrations.AlterField(
            model_name='financialproject',
            name='code',
            field=models.CharField(max_length=50, verbose_name='کد پروژه'),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='national_code',
            field=models.CharField(db_index=True, max_length=10, verbose_name='کد ملی (۱۰ رقم)'),
        ),
        migrations.AlterField(
            model_name='vehicledriverprofile',
            name='plate_number',
            field=models.CharField(db_index=True, max_length=30, verbose_name='شماره پلاک'),
        ),
        migrations.AddConstraint(
            model_name='financialproject',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'code'), name='unique_company_project_code'),
        ),
        migrations.AddConstraint(
            model_name='financialproject',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('code',), name='unique_global_project_code'),
        ),
        migrations.AddConstraint(
            model_name='monthlyworkperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False), ('warehouse_id__isnull', False)), fields=('company', 'warehouse_id', 'year_month'), name='unique_company_warehouse_year_month_period'),
        ),
        migrations.AddConstraint(
            model_name='monthlyworkperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False), ('warehouse_id__isnull', True)), fields=('company', 'year_month'), name='unique_company_year_month_period'),
        ),
        migrations.AddConstraint(
            model_name='monthlyworkperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('warehouse_id', 'year_month'), name='unique_warehouse_year_month_period'),
        ),
        migrations.AddConstraint(
            model_name='personnelprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'national_code'), name='unique_company_personnel_national_code'),
        ),
        migrations.AddConstraint(
            model_name='personnelprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('national_code',), name='unique_global_personnel_national_code'),
        ),
        migrations.AddConstraint(
            model_name='vehicledriverprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'plate_number'), name='unique_company_vehicle_plate'),
        ),
        migrations.AddConstraint(
            model_name='vehicledriverprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('plate_number',), name='unique_global_vehicle_plate'),
        ),
    ]
