# Generated by Django 5.0.4 on 2026-09-28 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0022_sync_user_companies_from_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان پرداخت'),
        ),
        migrations.AddField(
            model_name='expenseinvoice',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_invoices', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت\u200cکننده خزانه\u200cداری'),
        ),
        migrations.AddField(
            model_name='expenseinvoice',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری / سند پرداخت'),
        ),
        migrations.AddField(
            model_name='expenseinvoice',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='علت رد یا بازنگری فاکتور'),
        ),
        migrations.AlterField(
            model_name='expenseinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس کارمند'), ('pending_supervisor', 'در انتظار تایید سرپرست'), ('pending_accountant', 'در انتظار بررسی حسابدار'), ('pending_manager', 'در انتظار تایید مدیر'), ('ready_to_pay', 'تایید مدیر / آماده پرداخت'), ('paid', 'پرداخت\u200cشده توسط خزانه\u200cدار'), ('revision_required', 'نیازمند بازنگری و اصلاح'), ('rejected', 'رد شده')], default='draft', max_length=30, verbose_name='وضعیت فاکتور'),
        ),
        migrations.CreateModel(
            name='WorkflowAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='نوع مدل')),
                ('object_id', models.IntegerField(verbose_name='شناسه رکورد')),
                ('from_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت مبدأ')),
                ('to_status', models.CharField(max_length=50, verbose_name='وضعیت مقصد')),
                ('action', models.CharField(max_length=50, verbose_name='نوع اقدام')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='شرح / دلیل بازنگری یا رد')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='متادیتای الحاقی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='اقدام\u200cکننده')),
            ],
            options={
                'verbose_name': 'لاگ ممیزی گردش\u200cکار',
                'verbose_name_plural': 'لاگ\u200cهای ممیزی گردش\u200cکار',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='personnel_w_content_8b332d_idx'), models.Index(fields=['created_at'], name='personnel_w_created_245a77_idx')],
            },
        ),
    ]
