# Generated by Django 5.0.4 on 2026-09-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0023_expenseinvoice_paid_at_expenseinvoice_paid_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات و یادداشت تکمیلی'),
        ),
        migrations.AddField(
            model_name='vehicledriverprofile',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات و یادداشت تکمیلی'),
        ),
    ]
