# Generated by Django 5.0.4 on 2026-09-29 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0024_personnelprofile_notes_vehicledriverprofile_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelSectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='سمت / شغل در این بخش')),
                ('daily_base_wage', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='دستمزد روزانه مصوب این بخش (ریال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال در این بخش')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتساب به بخش')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='personnel.personnelprofile', verbose_name='پرسنل')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_assignments', to='personnel.financialproject', verbose_name='پروژه مالی/عملیاتی')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_assignments', to='personnel.projectsection', verbose_name='بخش/دپارتمان پروژه')),
            ],
            options={
                'verbose_name': 'انتساب پرسنل به بخش',
                'verbose_name_plural': 'انتساب\u200cهای پرسنل به بخش\u200cها',
                'unique_together': {('personnel', 'section')},
            },
        ),
    ]
