# Generated by Django 5.0.4 on 2026-09-07 13:18

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('requires_password_change', models.BooleanField(default=True)),
                ('password_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('operational_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True, verbose_name='شرکت متبوع')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='تصویر پرسنلی')),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='گروه خونی')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس اضطراری')),
                ('ui_preferences', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_users', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('view_sys_dashboard', 'داشبورد مانیتورینگ کلی'), ('view_sys_users', 'مدیریت کاربران و نقش\u200cها'), ('view_sys_projects', 'مدیریت انبارها و پروژه\u200cها'), ('view_sys_id_cards', 'صدور کارت پرسنلی'), ('view_sys_counter', 'میزکار شمارش کور'), ('view_sys_supervisor', 'کارتابل سرپرست شمارش'), ('view_sys_manager_review', 'بررسی نهایی مدیر'), ('view_sys_export', 'صدور فایل تغذیه'), ('view_sys_recounts', 'بررسی مغایرت و بازشماری'), ('view_sys_settings', 'تنظیمات سیستم'), ('view_sys_reports', 'گزارش\u200cساز'), ('view_sys_personnel', 'مدیریت پرسنل و کارگزینی'), ('view_sys_personnel_attendance', 'ثبت کارکرد پرسنل'), ('view_sys_fleet_attendance', 'ثبت کارکرد ناوگان و ماشین\u200cآلات'), ('view_sys_payroll', 'محاسبات حقوق و دستمزد پرسنل'), ('view_sys_fleet_settlement', 'تسویه و محاسبات مالی ناوگان'), ('view_wh_dashboard', 'داشبورد انبار'), ('view_wh_docs', 'مدیریت کالا (انبار)'), ('view_wh_dispatch', 'تخصیص کالا (انبار)'), ('view_wh_attendance', 'ثبت کارکرد و سرویس ناوگان (انبار)'), ('view_wh_customs', 'فیلدهای مالی و گمرکی (انبار)'), ('view_wh_doc_approvals', 'تاییدات سرپرست اسناد (انبار)'), ('view_wh_feeding', 'مدیریت و تغذیه MT (انبار)'), ('view_wh_feed_approvals', 'تاییدات سرپرست تغذیه (انبار)'), ('view_wh_labels', 'چاپ مجدد و اسکن لیبل (انبار)'), ('view_wh_label_designer', 'طراحی و کانفیگ لیبل (انبار)'), ('view_wh_audit', 'رهگیری تغییرات و ممیزی (انبار)'), ('view_wh_settings', 'تنظیمات انبار'), ('view_sys_treasury', 'کارتابل خزانه\u200cداری و پرداخت'), ('perm_doc_approve_action', 'تایید، رد و ثبت امضای اسناد'), ('perm_feed_approve_action', 'تایید و اعمال فیدهای تغذیه/گمرکی'), ('perm_inventory_finalize', 'تایید نهایی و بستن دوره\u200cهای انبارگردانی'), ('perm_lock_work_period', 'قفل و تایید نهایی کارکرد ماهانه'), ('perm_approve_personnel_supervisor', 'تایید مرحله سرپرست انبار برای پرسنل'), ('perm_approve_personnel_manager', 'تایید مرحله اول (عملیاتی) پرسنل'), ('perm_approve_personnel_finance', 'تایید مرحله دوم (مالی و بانکی) پرسنل'), ('perm_approve_fleet_supervisor', 'تایید مرحله سرپرست انبار برای ناوگان'), ('perm_approve_fleet_manager', 'تایید مرحله اول (عملیاتی) ناوگان و خودروها'), ('perm_approve_fleet_finance', 'تایید مرحله دوم (مالی و بانکی) ناوگان و خودروها'), ('perm_manager_payment_authorize', 'صدور مجوز پرداخت نهایی مدیر شرکت'), ('perm_treasury_disburse_action', 'ثبت واریز و تسویه نهایی خزانه\u200cداری'), ('perm_rollback_data', 'بازگردانی و احیای جامع داده\u200cها'), ('perm_rollback_single', 'بازگردانی تکی یک فیلد یا سند'), ('perm_rollback_bulk', 'بازگردانی گروهی و زمانی تراکنش\u200cها'), ('perm_restore_deleted', 'احیای داده\u200cهای حذف\u200cشده'), ('perm_sys_backup_manage', 'ایجاد و مدیریت فایل\u200cهای پشتیبان'), ('perm_sys_backup_restore', 'بازیابی پایگاه داده'), ('perm_sys_audit_export', 'خروجی گرفتن و آرشیو لاگ\u200cهای ممیزی'), ('perm_sys_purge_logs', 'پاکسازی و حذف قطعی لاگ\u200cهای ممیزی'), ('perm_sys_hard_delete', 'حذف فیزیکی و قطعی داده\u200cها'), ('perm_sys_emergency_freeze', 'فریز اضطراری و قفل سراسری انبارها'), ('perm_sys_factory_reset', 'بازنشانی مقادیر اولیه و ریست سیستم')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فارسی')),
                ('color', models.CharField(default='#94a3b8', max_length=7, verbose_name='رنگ سازمانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.customrole', verbose_name='نقش والد')),
            ],
            options={
                'verbose_name': 'نقش سازمانی',
                'verbose_name_plural': 'نقش\u200cهای سازمانی',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='SoDPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_module', models.CharField(choices=accounts.models.get_app_module_choices, db_index=True, default='personnel', max_length=50, verbose_name='ماژول کلان')),
                ('role_code', models.CharField(db_index=True, max_length=60, verbose_name='کد نقش سازمانی')),
                ('role_title_fa', models.CharField(blank=True, max_length=150, verbose_name='عنوان فارسی نقش')),
                ('page_route', models.CharField(db_index=True, max_length=150, verbose_name='مسیر صفحه فرانت\u200cاند')),
                ('action_code', models.CharField(db_index=True, max_length=100, verbose_name='کد عملیات / اقدام')),
                ('action_title_fa', models.CharField(blank=True, max_length=255, verbose_name='عنوان فارسی عملیات')),
                ('is_prohibited', models.BooleanField(default=True, verbose_name='آیا این اقدام خط قرمز و ممنوع است؟')),
                ('prohibition_reason_fa', models.TextField(blank=True, verbose_name='علت و پیام ممیزی فارسی ممنوعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'قانون تفکیک وظایف (SoD Policy)',
                'verbose_name_plural': 'ماتریس قوانین تفکیک وظایف (SoD Policies)',
                'ordering': ['app_module', 'role_code', 'page_route', 'action_code'],
                'unique_together': {('app_module', 'role_code', 'page_route', 'action_code')},
            },
        ),
        migrations.CreateModel(
            name='UserTableViewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('view_name', models.CharField(max_length=100)),
                ('columns_state', models.JSONField(default=list)),
                ('is_last_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نمای جدول',
                'verbose_name_plural': 'نماهای جدول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام کاربری اقدام\u200cکننده در زمان رویداد')),
                ('actor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی اقدام\u200cکننده در زمان رویداد')),
                ('warehouse_id', models.IntegerField(blank=True, db_column='warehouse_id', db_index=True, null=True, verbose_name='شناسهٔ انبار مرتبط')),
                ('module', models.CharField(choices=accounts.models.get_audit_module_choices, db_index=True, default='system', max_length=50, verbose_name='ماژول')),
                ('action', models.CharField(choices=[('CREATE', 'ایجاد رکورد'), ('UPDATE', 'ویرایش رکورد'), ('DELETE', 'حذف رکورد'), ('BULK_UPDATE', 'ویرایش گروهی'), ('APPROVE', 'تایید سرپرست'), ('REJECT', 'رد درخواست'), ('RECOUNT', 'دستور بازشماری'), ('PRINT', 'چاپ لیبل / گزارش'), ('EXPORT', 'خروجی اکسل/CSV'), ('IMPORT', 'تزریق / ایمپورت داده'), ('ROLLBACK', 'بازگردانی اطلاعات')], db_index=True, default='UPDATE', max_length=50, verbose_name='نوع عملیات')),
                ('severity', models.CharField(choices=[('info', 'عادی (اطلاع\u200cرسانی)'), ('warning', 'هشدار (تغییرات محدود/حساس)'), ('critical', 'بحرانی (حذف داده / تغییر دسترسی\u200cها)')], db_index=True, default='info', max_length=20, verbose_name='سطح اهمیت')),
                ('target_model', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='مدل هدف')),
                ('target_object_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='شناسه رکورد هدف')),
                ('target_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='شرح رکورد هدف')),
                ('before_state', models.JSONField(blank=True, null=True, verbose_name='وضعیت قبل از تغییر')),
                ('after_state', models.JSONField(blank=True, null=True, verbose_name='وضعیت بعد از تغییر')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات و توضیحات رویداد')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس آی\u200cپی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت رویداد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر اقدام\u200cکننده')),
            ],
            options={
                'verbose_name': 'لاگ ممیزی عملیات',
                'verbose_name_plural': 'لاگ\u200cهای ممیزی عملیات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'created_at'], name='accounts_au_module_0c9200_idx'), models.Index(fields=['action', 'created_at'], name='accounts_au_action_c683b9_idx'), models.Index(fields=['severity', 'created_at'], name='accounts_au_severit_6842ce_idx'), models.Index(fields=['warehouse_id', 'created_at'], name='accounts_au_warehou_2f992b_idx'), models.Index(fields=['user', 'created_at'], name='accounts_au_user_id_7b1069_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='کلید یکتای سشن')),
                ('tab_id', models.CharField(db_index=True, max_length=120, verbose_name='شناسه تب کلاینت')),
                ('device_model', models.CharField(default='ناشناخته', max_length=200, verbose_name='مدل دستگاه')),
                ('os_name', models.CharField(default='Unknown', max_length=100, verbose_name='سیستم\u200cعامل')),
                ('browser_name', models.CharField(default='Unknown', max_length=100, verbose_name='مرورگر')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس آی\u200cپی')),
                ('app_scope', models.CharField(default='warehouse', max_length=50, verbose_name='قلمرو فعال (انبار/مالی)')),
                ('active_role', models.CharField(default='counter', max_length=50, verbose_name='نقش فعال')),
                ('pending_queue_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تراکنش\u200cهای معلق صف')),
                ('conflict_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تداخل\u200cهای حل\u200cنشده')),
                ('is_revoked', models.BooleanField(db_index=True, default=False, verbose_name='آیا نشست ابطال شده است؟')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین پالس زنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع نشست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر متصل')),
            ],
            options={
                'verbose_name': 'نشست فعال دستگاه',
                'verbose_name_plural': 'نشست\u200cهای فعال دستگاه\u200cها و ناوگان',
                'ordering': ['-last_heartbeat'],
                'indexes': [models.Index(fields=['user', 'is_revoked', 'last_heartbeat'], name='accounts_us_user_id_90d459_idx'), models.Index(fields=['session_key'], name='accounts_us_session_8f4eac_idx'), models.Index(fields=['tab_id'], name='accounts_us_tab_id_e4fcb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(db_index=True, max_length=150, verbose_name='نام کاربری ورودی')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='آدرس آی\u200cپی')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='مشخصات مرورگر/دستگاه')),
                ('device_model', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='مدل دستگاه/سخت\u200cافزار')),
                ('status', models.CharField(choices=[('SUCCESS', 'ورود موفق'), ('DAILY_ACTIVE', 'حضور روزانه'), ('FAILED_CREDENTIALS', 'کلمه عبور نادرست'), ('FAILED_LOCKED', 'مسدود شده توسط سیستم ضدنفوذ'), ('FAILED_INACTIVE', 'حساب کاربری غیرفعال'), ('LOGOUT', 'خروج امن')], db_index=True, default='SUCCESS', max_length=30, verbose_name='وضعیت ورود')),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='علت شکست')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتای تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان رویداد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ ورود کاربر',
                'verbose_name_plural': 'لاگ\u200cهای ورود کاربران',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_us_user_id_895cc0_idx'), models.Index(fields=['status', 'created_at'], name='accounts_us_status_6728cf_idx'), models.Index(fields=['ip_address', 'created_at'], name='accounts_us_ip_addr_c708b1_idx'), models.Index(fields=['device_model', 'created_at'], name='accounts_us_device__1fe0ce_idx')],
            },
        ),
    ]
