# Generated by Django 5.0.4 on 2026-07-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requires_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
