# Generated by Django 5.0.4 on 2026-07-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_requires_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ui_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
