# Generated by Django 5.0.4 on 2026-09-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='company_id', db_index=True, null=True, verbose_name='شناسهٔ شرکت مرتبط'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company_id', 'created_at'], name='accounts_au_company_db2e10_idx'),
        ),
    ]
