# Generated by Django 5.0.4 on 2026-07-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_sys_dashboard', 'دسترسی به تب داشبورد مانیتورینگ کلی'), ('view_sys_users', 'دسترسی به تب مدیریت کاربران'), ('view_sys_projects', 'دسترسی به تب مدیریت انبارها'), ('view_sys_id_cards', 'دسترسی به تب صدور کارت پرسنلی'), ('view_sys_counter', 'دسترسی به تب میزکار شمارش کور'), ('view_sys_supervisor', 'دسترسی به تب کارتابل سرپرست شمارش'), ('view_sys_manager_review', 'دسترسی به تب بررسی نهایی مدیر'), ('view_sys_export', 'دسترسی به تب صدور فایل تغذیه'), ('view_sys_recounts', 'دسترسی به تب بررسی مغایرت و بازشماری'), ('view_sys_settings', 'دسترسی به تب تنظیمات سیستم'), ('view_wh_dashboard', 'دسترسی به تب داشبورد انبار'), ('view_wh_docs', 'دسترسی به تب مدیریت کالا (انبار)'), ('view_wh_dispatch', 'دسترسی به تب تخصیص کالا (انبار)'), ('view_wh_customs', 'دسترسی به تب فیلدهای مالی/گمرکی (انبار)'), ('view_wh_doc_approvals', 'دسترسی به تب تاییدات سرپرست (انبار)'), ('view_wh_feeding', 'دسترسی به تب مدیریت و تغذیه MT (انبار)'), ('view_wh_feed_approvals', 'دسترسی به تب تاییدات سرپرست تغذیه (انبار)'), ('view_wh_labels', 'دسترسی به تب چاپ مجدد و اسکن لیبل (انبار)'), ('view_wh_label_designer', 'دسترسی به تب طراحی و کانفیگ لیبل (انبار)'), ('view_wh_audit', 'دسترسی به تب رهگیری تغییرات (انبار)'), ('perm_sys_settings', 'دسترسی به تنظیمات کلان سیستم'), ('perm_sys_logs', 'مشاهده لاگ\u200cهای امنیتی (Audit)'), ('perm_wh_create', 'تعریف کارگاه/انبار جدید'), ('perm_wh_edit', 'ویرایش مشخصات انبارها'), ('perm_wh_freeze', 'فریز کردن و توقف عملیات انبار'), ('perm_rec_import', 'تزریق و آپلود فایل پایه (Excel)'), ('perm_rec_dispatch', 'تخصیص رکورد به شمارشگر میدانی'), ('perm_rec_label', 'صدور دستور چاپ لیبل و QR Code'), ('perm_rec_recount', 'صدور دستور بازشماری (مغایرت)'), ('perm_usr_add', 'ثبت پرسنل جدید'), ('perm_usr_edit', 'ویرایش پرونده پرسنلی'), ('perm_usr_role', 'تغییر ساختار سازمانی و نقش\u200cها')]},
        ),
    ]
