# Generated by Django 5.0.4 on 2026-07-18 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
