# Generated by Django 5.0.4 on 2026-07-23 21:20

from django.db import migrations


def create_initial_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    # Define roles and their corresponding codenames
    roles_permissions = {
        'مدیر سیستم': [
            'view_sys_dashboard', 'view_sys_users', 'view_sys_projects',
            'view_sys_settings', 'view_wh_settings', 'view_wh_label_designer'
        ],
        'سرپرست انبار': [
            'view_wh_dashboard', 'view_wh_docs', 'view_wh_doc_approvals',
            'view_wh_audit', 'view_wh_dispatch', 'view_wh_customs',
            'view_wh_feeding', 'view_wh_feed_approvals'
        ],
        'انباردار': [
            'view_wh_docs', 'view_wh_dispatch', 'view_wh_labels'
        ],
        'سرپرست شمارش': [
            'view_sys_supervisor', 'view_sys_recounts'
        ],
        'شمارشگر': [
            'view_sys_counter'
        ],
        'مدیر پروژه': [
            'view_sys_dashboard', 'view_sys_manager_review', 'view_wh_dashboard'
        ],
        'اپراتور صدور': [
            'view_sys_export'
        ]
    }
    
    for role_name, perms in roles_permissions.items():
        group, created = Group.objects.get_or_create(name=role_name)
        # Find permissions (we assume content types are already created or we just filter by codename)
        # Note: Since permissions might be created after models in initial migrations,
        # it's usually safe here as this is migration 0009.
        permissions = Permission.objects.filter(codename__in=perms)
        group.permissions.set(permissions)

def remove_initial_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    roles = [
        'مدیر سیستم', 'سرپرست انبار', 'انباردار', 
        'سرپرست شمارش', 'شمارشگر', 'مدیر پروژه', 'اپراتور صدور'
    ]
    Group.objects.filter(name__in=roles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_password_changed_at'),
    ]

    operations = [
        migrations.RunPython(create_initial_roles, remove_initial_roles),
    ]
