# Generated by Django 5.0.4 on 2026-07-24 16:33

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_initial_roles'),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فارسی')),
                ('color', models.CharField(default='#94a3b8', max_length=7, verbose_name='رنگ سازمانی')),
                ('is_system', models.BooleanField(default=False, verbose_name='نقش سیستمی (غیرقابل حذف)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.customrole', verbose_name='نقش والد')),
            ],
            options={
                'verbose_name': 'نقش سازمانی',
                'verbose_name_plural': 'نقش\u200cهای سازمانی',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
