# Generated by Django 5.0.4 on 2026-07-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_populate_custom_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrole',
            name='is_system',
        ),
    ]
