# Generated by Django 5.0.4 on 2026-07-26 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customrole_is_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTableViewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('view_name', models.CharField(max_length=100)),
                ('columns_state', models.JSONField(default=list)),
                ('is_last_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نمای جدول',
                'verbose_name_plural': 'نماهای جدول',
                'ordering': ['-created_at'],
            },
        ),
    ]
