# Generated by Django 5.0.4 on 2026-08-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='گروه خونی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس اضطراری'),
        ),
    ]
