# Generated by Django 5.0.4 on 2026-08-19 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_blood_type_customuser_emergency_contact'),
        ('warehouses', '0003_add_label_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('docs', 'مدیریت کالا'), ('dispatch', 'تخصیص کالا'), ('customs', 'گمرک و مالی'), ('feeding', 'تغذیه MT'), ('labels', 'لیبلینگ و چاپ'), ('counter', 'میزکار شمارش'), ('supervisor', 'کارتابل سرپرست'), ('manager', 'بررسی مدیر'), ('users', 'کاربران و نقش\u200cها'), ('warehouses', 'مدیریت انبارها'), ('settings', 'تنظیمات'), ('system', 'رویداد سیستمی')], db_index=True, default='system', max_length=50, verbose_name='ماژول')),
                ('action', models.CharField(choices=[('CREATE', 'ایجاد (Create)'), ('UPDATE', 'ویرایش (Update)'), ('DELETE', 'حذف (Delete)'), ('BULK_UPDATE', 'ویرایش گروهی (Bulk Update)'), ('APPROVE', 'تایید (Approve)'), ('REJECT', 'رد (Reject)'), ('RECOUNT', 'بازشماری (Recount)'), ('PRINT', 'چاپ لیبل (Print)'), ('EXPORT', 'خروجی اکسل/گزارش (Export)'), ('IMPORT', 'ورود اکسل/داده (Import)'), ('ROLLBACK', 'بازگردانی (Rollback)'), ('AUTH', 'احراز هویت / دسترسی')], db_index=True, default='UPDATE', max_length=50, verbose_name='نوع عملیات')),
                ('severity', models.CharField(choices=[('info', 'عادی (Info)'), ('warning', 'هشدار (Warning)'), ('critical', 'بحرانی (Critical)')], db_index=True, default='info', max_length=20, verbose_name='سطح اهمیت')),
                ('target_model', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='مدل هدف')),
                ('target_object_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='شناسه رکورد هدف')),
                ('target_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان رکورد هدف')),
                ('before_state', models.JSONField(blank=True, null=True, verbose_name='وضعیت قبل')),
                ('after_state', models.JSONField(blank=True, null=True, verbose_name='وضعیت بعد')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات رویداد')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس آی\u200cپی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان رویداد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر اقدام\u200cکننده')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='warehouses.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'لاگ ممیزی و رهگیری',
                'verbose_name_plural': 'لاگ\u200cهای ممیزی و رهگیری',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', '-created_at'], name='accounts_au_module_a97c4b_idx'), models.Index(fields=['action', '-created_at'], name='accounts_au_action_f18cdc_idx'), models.Index(fields=['severity', '-created_at'], name='accounts_au_severit_c4c321_idx'), models.Index(fields=['user', '-created_at'], name='accounts_au_user_id_14f360_idx'), models.Index(fields=['warehouse', '-created_at'], name='accounts_au_warehou_62946a_idx'), models.Index(fields=['target_model', 'target_object_id'], name='accounts_au_target__fd1af7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(db_index=True, max_length=150, verbose_name='نام کاربری وارد شده')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='آدرس آی\u200cپی')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='مشخصات کلاینت / مرورگر')),
                ('status', models.CharField(choices=[('SUCCESS', 'ورود موفق'), ('FAILED_CREDENTIALS', 'کلمه عبور اشتباه'), ('FAILED_LOCKED', 'مسدودسازی موقت (Axes)'), ('FAILED_INACTIVE', 'حساب غیرفعال'), ('LOGOUT', 'خروج کاربر')], db_index=True, default='SUCCESS', max_length=30, verbose_name='وضعیت ورود')),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='علت شکست')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ ورود کاربر',
                'verbose_name_plural': 'لاگ\u200cهای ورود کاربران',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_364f67_idx'), models.Index(fields=['status', '-created_at'], name='accounts_us_status_c7131e_idx'), models.Index(fields=['ip_address', '-created_at'], name='accounts_us_ip_addr_a658d7_idx')],
            },
        ),
    ]
