# Generated by Django 5.0.4 on 2026-08-19 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auditlog_userloginlog'),
        ('warehouses', '0003_add_label_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'لاگ ممیزی عملیات', 'verbose_name_plural': 'لاگ\u200cهای ممیزی عملیات'},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_module_a97c4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_action_f18cdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_severit_c4c321_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_user_id_14f360_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_warehou_62946a_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_target__fd1af7_idx',
        ),
        migrations.RemoveIndex(
            model_name='userloginlog',
            name='accounts_us_user_id_364f67_idx',
        ),
        migrations.RemoveIndex(
            model_name='userloginlog',
            name='accounts_us_status_c7131e_idx',
        ),
        migrations.RemoveIndex(
            model_name='userloginlog',
            name='accounts_us_ip_addr_a658d7_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'ایجاد رکورد'), ('UPDATE', 'ویرایش رکورد'), ('DELETE', 'حذف رکورد'), ('BULK_UPDATE', 'ویرایش گروهی'), ('APPROVE', 'تایید سرپرست'), ('REJECT', 'رد درخواست'), ('RECOUNT', 'دستور بازشماری'), ('PRINT', 'چاپ لیبل / گزارش'), ('EXPORT', 'خروجی اکسل/CSV'), ('IMPORT', 'تزریق / ایمپورت داده'), ('ROLLBACK', 'بازگردانی اطلاعات')], db_index=True, default='UPDATE', max_length=50, verbose_name='نوع عملیات'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='after_state',
            field=models.JSONField(blank=True, null=True, verbose_name='وضعیت بعد از تغییر'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='before_state',
            field=models.JSONField(blank=True, null=True, verbose_name='وضعیت قبل از تغییر'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت رویداد'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='جزئیات و توضیحات رویداد'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('docs', 'مدیریت کالا (انبار)'), ('dispatch', 'تخصیص کالا (انبار)'), ('customs', 'فیلدهای مالی/گمرکی (انبار)'), ('feeding', 'تغذیه سامانه\u200cهای MT (انبار)'), ('labels', 'لیبلینگ و بارکد (انبار)'), ('counter', 'میزکار شمارش کور'), ('supervisor', 'کارتابل سرپرست شمارش'), ('manager', 'بررسی نهایی مدیر'), ('users', 'کاربران و نقش\u200cها'), ('warehouses', 'مدیریت انبارها'), ('settings', 'تنظیمات سیستم و انبار'), ('system', 'رویدادهای سیستمی')], db_index=True, default='system', max_length=50, verbose_name='ماژول'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('info', 'عادی (اطلاع\u200cرسانی)'), ('warning', 'هشدار (تغییرات محدود/حساس)'), ('critical', 'بحرانی (حذف داده / تغییر دسترسی\u200cها)')], db_index=True, default='info', max_length=20, verbose_name='سطح اهمیت'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شرح رکورد هدف'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='warehouses.warehouse', verbose_name='انبار مرتبط'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان رویداد'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='متادیتای تکمیلی'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'ورود موفق'), ('FAILED_CREDENTIALS', 'کلمه عبور نادرست'), ('FAILED_LOCKED', 'مسدود شده توسط سیستم ضدنفوذ'), ('FAILED_INACTIVE', 'حساب کاربری غیرفعال'), ('LOGOUT', 'خروج امن')], db_index=True, default='SUCCESS', max_length=30, verbose_name='وضعیت ورود'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='مشخصات مرورگر/دستگاه'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='username_attempted',
            field=models.CharField(db_index=True, max_length=150, verbose_name='نام کاربری ورودی'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module', 'created_at'], name='accounts_au_module_0c9200_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='accounts_au_action_c683b9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'created_at'], name='accounts_au_severit_6842ce_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['warehouse', 'created_at'], name='accounts_au_warehou_2f992b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='accounts_au_user_id_7b1069_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['user', 'created_at'], name='accounts_us_user_id_895cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['status', 'created_at'], name='accounts_us_status_6728cf_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='accounts_us_ip_addr_c708b1_idx'),
        ),
    ]
