# Generated by Django 5.0.4 on 2026-08-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی اقدام\u200cکننده در زمان رویداد'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام کاربری اقدام\u200cکننده در زمان رویداد'),
        ),
    ]
