# Generated by Django 5.0.4 on 2026-08-20 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_sys_dashboard', 'داشبورد مانیتورینگ کلی'), ('view_sys_users', 'مدیریت کاربران و نقش\u200cها'), ('view_sys_projects', 'مدیریت انبارها و پروژه\u200cها'), ('view_sys_id_cards', 'صدور کارت پرسنلی'), ('view_sys_counter', 'میزکار شمارش کور'), ('view_sys_supervisor', 'کارتابل سرپرست شمارش'), ('view_sys_manager_review', 'بررسی نهایی مدیر'), ('view_sys_export', 'صدور فایل تغذیه'), ('view_sys_recounts', 'بررسی مغایرت و بازشماری'), ('view_sys_settings', 'تنظیمات سیستم'), ('view_sys_reports', 'گزارش\u200cساز'), ('view_wh_dashboard', 'داشبورد انبار'), ('view_wh_docs', 'مدیریت کالا (انبار)'), ('view_wh_dispatch', 'تخصیص کالا (انبار)'), ('view_wh_customs', 'فیلدهای مالی و گمرکی (انبار)'), ('view_wh_doc_approvals', 'تاییدات سرپرست اسناد (انبار)'), ('view_wh_feeding', 'مدیریت و تغذیه MT (انبار)'), ('view_wh_feed_approvals', 'تاییدات سرپرست تغذیه (انبار)'), ('view_wh_labels', 'چاپ مجدد و اسکن لیبل (انبار)'), ('view_wh_label_designer', 'طراحی و کانفیگ لیبل (انبار)'), ('view_wh_audit', 'رهگیری تغییرات و ممیزی (انبار)'), ('view_wh_settings', 'تنظیمات انبار'), ('perm_doc_approve_action', 'تایید، رد و ثبت امضای اسناد'), ('perm_feed_approve_action', 'تایید و اعمال فیدهای تغذیه/گمرکی'), ('perm_inventory_finalize', 'تایید نهایی و بستن دوره\u200cهای انبارگردانی'), ('perm_rollback_data', 'بازگردانی و احیای جامع داده\u200cها'), ('perm_rollback_single', 'بازگردانی تکی یک فیلد یا سند'), ('perm_rollback_bulk', 'بازگردانی گروهی و زمانی تراکنش\u200cها'), ('perm_restore_deleted', 'احیای داده\u200cهای حذف\u200cشده'), ('perm_sys_backup_manage', 'ایجاد و مدیریت فایل\u200cهای پشتیبان'), ('perm_sys_backup_restore', 'بازیابی پایگاه داده'), ('perm_sys_audit_export', 'خروجی گرفتن و آرشیو لاگ\u200cهای ممیزی'), ('perm_sys_purge_logs', 'پاکسازی و حذف قطعی لاگ\u200cهای ممیزی'), ('perm_sys_hard_delete', 'حذف فیزیکی و قطعی داده\u200cها'), ('perm_sys_emergency_freeze', 'فریز اضطراری و قفل سراسری انبارها'), ('perm_sys_factory_reset', 'بازنشانی مقادیر اولیه و ریست سیستم')]},
        ),
    ]
