# Generated by Django 5.0.4 on 2026-08-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='device_model',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='مدل دستگاه/سخت\u200cافزار'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'ورود موفق'), ('DAILY_ACTIVE', 'حضور روزانه'), ('FAILED_CREDENTIALS', 'کلمه عبور نادرست'), ('FAILED_LOCKED', 'مسدود شده توسط سیستم ضدنفوذ'), ('FAILED_INACTIVE', 'حساب کاربری غیرفعال'), ('LOGOUT', 'خروج امن')], db_index=True, default='SUCCESS', max_length=30, verbose_name='وضعیت ورود'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['device_model', 'created_at'], name='accounts_us_device__1fe0ce_idx'),
        ),
    ]
