# Generated by Django 5.0.4 on 2026-09-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoDPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_module', models.CharField(choices=[('warehouse', 'سامانه انبارداری و انبارگردانی'), ('personnel', 'سامانه کارکرد، مالی و خزانه\u200cداری')], db_index=True, default='personnel', max_length=50, verbose_name='ماژول کلان')),
                ('role_code', models.CharField(db_index=True, max_length=60, verbose_name='کد نقش سازمانی')),
                ('role_title_fa', models.CharField(blank=True, max_length=150, verbose_name='عنوان فارسی نقش')),
                ('page_route', models.CharField(db_index=True, max_length=150, verbose_name='مسیر صفحه فرانت\u200cاند')),
                ('action_code', models.CharField(db_index=True, max_length=100, verbose_name='کد عملیات / اقدام')),
                ('action_title_fa', models.CharField(blank=True, max_length=255, verbose_name='عنوان فارسی عملیات')),
                ('is_prohibited', models.BooleanField(default=True, verbose_name='آیا این اقدام خط قرمز و ممنوع است؟')),
                ('prohibition_reason_fa', models.TextField(blank=True, verbose_name='علت و پیام ممیزی فارسی ممنوعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'قانون تفکیک وظایف (SoD Policy)',
                'verbose_name_plural': 'ماتریس قوانین تفکیک وظایف (SoD Policies)',
                'ordering': ['app_module', 'role_code', 'page_route', 'action_code'],
                'unique_together': {('app_module', 'role_code', 'page_route', 'action_code')},
            },
        ),
    ]
