# Generated by Django 5.0.4 on 2026-09-05 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_sodpolicyrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='کلید یکتای سشن')),
                ('tab_id', models.CharField(db_index=True, max_length=120, verbose_name='شناسه تب کلاینت')),
                ('device_model', models.CharField(default='ناشناخته', max_length=200, verbose_name='مدل دستگاه')),
                ('os_name', models.CharField(default='Unknown', max_length=100, verbose_name='سیستم\u200cعامل')),
                ('browser_name', models.CharField(default='Unknown', max_length=100, verbose_name='مرورگر')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس آی\u200cپی')),
                ('app_scope', models.CharField(default='warehouse', max_length=50, verbose_name='قلمرو فعال (انبار/مالی)')),
                ('active_role', models.CharField(default='counter', max_length=50, verbose_name='نقش فعال')),
                ('pending_queue_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تراکنش\u200cهای معلق صف')),
                ('conflict_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تداخل\u200cهای حل\u200cنشده')),
                ('is_revoked', models.BooleanField(db_index=True, default=False, verbose_name='آیا نشست ابطال شده است؟')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین پالس زنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع نشست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر متصل')),
            ],
            options={
                'verbose_name': 'نشست فعال دستگاه',
                'verbose_name_plural': 'نشست\u200cهای فعال دستگاه\u200cها و ناوگان',
                'ordering': ['-last_heartbeat'],
                'indexes': [models.Index(fields=['user', 'is_revoked', 'last_heartbeat'], name='accounts_us_user_id_90d459_idx'), models.Index(fields=['session_key'], name='accounts_us_session_8f4eac_idx'), models.Index(fields=['tab_id'], name='accounts_us_tab_id_e4fcb7_idx')],
            },
        ),
    ]
