# Generated by Django 5.0.4 on 2026-09-07 00:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_userdevicesession'),
    ]

    operations = [
        # فاز ۲ — بریدن یال‌های هسته → انبار، با صفر مهاجرت داده.
        #
        # همهٔ عملیاتِ زیر فقط state را به‌روز می‌کنند (`SeparateDatabaseAndState`)،
        # پس هیچ ALTER/DROP/CREATE روی دیتابیس تولیدی اجرا نمی‌شود:
        #   - جدول M2M `accounts_customuser_assigned_warehouses` دست‌نخورده می‌ماند؛
        #     مالکیت آن در `warehouses/migrations/0005` به اپ انبار منتقل می‌شود.
        #   - ستون `auditlog.warehouse_id` (که پیش‌تر ستونِ FK به `Warehouse` بود)
        #     همان‌جا و با همان ایندکس باقی می‌ماند؛ فقط در state به عدد صحیح ساده
        #     تبدیل می‌شود تا هسته به ماژول انبار وابسته نماند.
        #   - ایندکس `accounts_au_warehou_2f992b_idx` همان ایندکس است و در DB حفظ
        #     می‌شود (در state به `warehouse_id` اشاره می‌کند).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='auditlog',
                    name='accounts_au_warehou_2f992b_idx',
                ),
                migrations.RemoveField(
                    model_name='auditlog',
                    name='warehouse',
                ),
                migrations.RemoveField(
                    model_name='customuser',
                    name='assigned_warehouses',
                ),
                migrations.AddField(
                    model_name='auditlog',
                    name='warehouse_id',
                    field=models.IntegerField(blank=True, db_column='warehouse_id', db_index=True, null=True, verbose_name='شناسهٔ انبار مرتبط'),
                ),
                migrations.AlterField(
                    model_name='auditlog',
                    name='module',
                    field=models.CharField(choices=accounts.models.get_audit_module_choices, db_index=True, default='system', max_length=50, verbose_name='ماژول'),
                ),
                migrations.AddIndex(
                    model_name='auditlog',
                    index=models.Index(fields=['warehouse_id', 'created_at'], name='accounts_au_warehou_2f992b_idx'),
                ),
            ],
        ),
    ]
