# Generated by Django 5.0.4 on 2026-09-07 02:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_remove_auditlog_accounts_au_warehou_2f992b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sodpolicyrule',
            name='app_module',
            field=models.CharField(choices=accounts.models.get_app_module_choices, db_index=True, default='personnel', max_length=50, verbose_name='ماژول کلان'),
        ),
    ]
