# Generated by Django 5.0.4 on 2026-09-07 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('operator_company', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_users', models.ManyToManyField(blank=True, db_table='accounts_customuser_assigned_warehouses', related_name='assigned_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='کاربران تخصیص\u200cیافته')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouses', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_warehouses', to=settings.AUTH_USER_MODEL)),
                ('parent_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_warehouses', to='warehouses.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='پیش\u200cفرض', max_length=100, verbose_name='نام تمپلیت')),
                ('width_mm', models.IntegerField(default=70, verbose_name='عرض لیبل (mm)')),
                ('height_mm', models.IntegerField(default=40, verbose_name='ارتفاع لیبل (mm)')),
                ('qr_source_field', models.CharField(default='fa_unic_code', max_length=100, verbose_name='فیلد منبع QR Code')),
                ('elements', models.JSONField(blank=True, default=list, verbose_name='المان\u200cهای بوم')),
                ('paper_type', models.CharField(choices=[('A4', 'کاغذ A4'), ('A3', 'کاغذ A3'), ('roll', 'رول حرارتی')], default='A4', max_length=10, verbose_name='نوع کاغذ')),
                ('grid_rows', models.IntegerField(default=7, verbose_name='تعداد سطر')),
                ('grid_cols', models.IntegerField(default=3, verbose_name='تعداد ستون')),
                ('margin_mm', models.IntegerField(default=5, verbose_name='حاشیه (mm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_templates', to='warehouses.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'قالب لیبل',
                'verbose_name_plural': 'قالب\u200cهای لیبل',
                'ordering': ['-updated_at'],
            },
        ),
    ]
