# Generated by Django 5.0.4 on 2026-09-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='company_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='شناسه شرکت مالک انبار'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام شرکت مالک'),
        ),
    ]
