# Generated by Django 5.0.4 on 2026-07-26 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='پیش\u200cفرض', max_length=100, verbose_name='نام تمپلیت')),
                ('width_mm', models.IntegerField(default=70, verbose_name='عرض لیبل (mm)')),
                ('height_mm', models.IntegerField(default=40, verbose_name='ارتفاع لیبل (mm)')),
                ('qr_source_field', models.CharField(default='fa_unic_code', max_length=100, verbose_name='فیلد منبع QR Code')),
                ('elements', models.JSONField(blank=True, default=list, verbose_name='المان\u200cهای بوم')),
                ('paper_type', models.CharField(choices=[('A4', 'کاغذ A4'), ('A3', 'کاغذ A3'), ('roll', 'رول حرارتی')], default='A4', max_length=10, verbose_name='نوع کاغذ')),
                ('grid_rows', models.IntegerField(default=7, verbose_name='تعداد سطر')),
                ('grid_cols', models.IntegerField(default=3, verbose_name='تعداد ستون')),
                ('margin_mm', models.IntegerField(default=5, verbose_name='حاشیه (mm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_templates', to='warehouses.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'قالب لیبل',
                'verbose_name_plural': 'قالب\u200cهای لیبل',
                'ordering': ['-updated_at'],
            },
        ),
    ]
