# Generated by Django 5.0.4 on 2026-09-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0020_counterparty_company_monthlyworkperiod_company_and_more'),
        ('warehouses', '0003_assign_warehouses_to_fars_alish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(
                blank=True,
                db_column='company_id',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='warehouses',
                to='personnel.company',
                verbose_name='شرکت مالک انبار'
            ),
        ),
    ]
