# Generated by Django 5.0.4 on 2026-09-07 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_split_settings_to_settings_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # فاز ۲ §۲.۱ — جابجایی مالکیت M2M به اپ انبار، با صفر مهاجرت داده.
        #
        # جدول `accounts_customuser_assigned_warehouses` از قبل روی دیتابیس موجود است
        # (از سمت اپ حساب ساخته شده بود) و ستون‌های آن (`customuser_id`, `warehouse_id`)
        # عیناً با M2M جدید روی `Warehouse` سازگارند. پس این عملیات فقط state را
        # به‌روز می‌کند و هیچ `CREATE TABLE` ای اجرا نمی‌کند. اکسسور
        # `user.assigned_warehouses` و `warehouse.assigned_users` بدون تغییر حفظ می‌شود.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='warehouse',
                    name='assigned_users',
                    field=models.ManyToManyField(blank=True, db_table='accounts_customuser_assigned_warehouses', related_name='assigned_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='کاربران تخصیص‌یافته'),
                ),
            ],
        ),
    ]
