# Generated by Django 5.0.4 on 2026-08-25 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان اعلان')),
                ('message', models.TextField(verbose_name='متن اعلان')),
                ('notification_type', models.CharField(db_index=True, default='mention', max_length=50, verbose_name='نوع اعلان')),
                ('target_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل هدف')),
                ('target_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه هدف')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='خوانده\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر دریافت\u200cکننده')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
