# Generated by Django 5.0.4 on 2026-09-07 13:18

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه همگام\u200cسازی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده (نرم)')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان گفتگو')),
                ('conv_type', models.CharField(choices=[('direct', 'گفتگوی دو\u200cنفره'), ('warehouse_group', 'گروه کاری انبار'), ('announcement', 'اطلاعیه عمومی')], default='direct', max_length=25, verbose_name='نوع گفتگو')),
                ('warehouse_id', models.IntegerField(blank=True, db_column='warehouse_id', db_index=True, null=True, verbose_name='شناسهٔ انبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('participants', models.ManyToManyField(blank=True, related_name='chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='اعضا')),
            ],
            options={
                'verbose_name': 'گفتگو / اتاق چت',
                'verbose_name_plural': 'گفتگوها / اتاق\u200cهای چت',
                'ordering': ['-updated_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GenericComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه همگام\u200cسازی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده (نرم)')),
                ('client_temp_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='شناسه یکتایی کلاینت')),
                ('object_id', models.CharField(max_length=100, verbose_name='شناسه موجودیت')),
                ('warehouse_id', models.IntegerField(blank=True, db_column='warehouse_id', db_index=True, null=True, verbose_name='شناسهٔ انبار')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='comment_attachments/%Y/%m/', verbose_name='پیوست')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع موجودیت')),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='comment_mentions', to=settings.AUTH_USER_MODEL, verbose_name='کاربران منشن\u200cشده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communications.genericcomment', verbose_name='پاسخ به نظر')),
            ],
            options={
                'verbose_name': 'یادداشت و نظر تعاملی',
                'verbose_name_plural': 'یادداشت\u200cها و نظرات تعاملی',
                'ordering': ['created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه همگام\u200cسازی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده (نرم)')),
                ('client_temp_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='شناسه یکتایی کلاینت')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن پیام')),
                ('is_system', models.BooleanField(default=False, verbose_name='پیام سیستمی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ارسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversation', verbose_name='گفتگو')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='خوانده\u200cشده توسط')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='communications.message', verbose_name='پاسخ به')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام گفتگو',
                'verbose_name_plural': 'پیام\u200cهای گفتگو',
                'ordering': ['created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه همگام\u200cسازی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده (نرم)')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین خواندن')),
                ('is_muted', models.BooleanField(default=False, verbose_name='بی\u200cصدا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_memberships', to='communications.conversation', verbose_name='گفتگو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_by_participants', to='communications.message', verbose_name='آخرین پیام خوانده\u200cشده')),
            ],
            options={
                'verbose_name': 'عضو گفتگو',
                'verbose_name_plural': 'اعضای گفتگو',
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه همگام\u200cسازی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده (نرم)')),
                ('file', models.FileField(upload_to='chat_attachments/%Y/%m/', verbose_name='فایل ضمیمه')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم بایت')),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100, verbose_name='نوع فایل')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='chat_attachments/thumbs/%Y/%m/', verbose_name='بندانگشتی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.message', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیوست پیام',
                'verbose_name_plural': 'پیوست\u200cهای پیام',
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['warehouse_id', 'conv_type', 'updated_at'], name='communicati_warehou_bf4b05_idx'),
        ),
        migrations.AddIndex(
            model_name='genericcomment',
            index=models.Index(fields=['content_type', 'object_id', 'created_at'], name='communicati_content_3e0d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='genericcomment',
            index=models.Index(fields=['warehouse_id', 'created_at'], name='communicati_warehou_651426_idx'),
        ),
        migrations.AddConstraint(
            model_name='genericcomment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_temp_id__isnull', False)), fields=('content_type', 'object_id', 'author', 'client_temp_id'), name='unique_generic_comment_client_temp_id'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='communicati_convers_b5d10e_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_temp_id__isnull', False)), fields=('conversation', 'sender', 'client_temp_id'), name='unique_message_client_temp_id'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_participant'),
        ),
    ]
