# Generated by Django 5.0.4 on 2026-08-24 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('contenttypes', '0001_initial'),
        ('warehouses', '0003_add_label_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='genericcomment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_temp_id__isnull', False)), fields=('content_type', 'object_id', 'author', 'client_temp_id'), name='unique_generic_comment_client_temp_id'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_temp_id__isnull', False)), fields=('conversation', 'sender', 'client_temp_id'), name='unique_message_client_temp_id'),
        ),
    ]
