# Generated by Django 5.0.4 on 2026-08-24 21:36

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_participants_and_read_state(apps, schema_editor):
    Conversation = apps.get_model('communications', 'Conversation')
    ConversationParticipant = apps.get_model('communications', 'ConversationParticipant')
    Message = apps.get_model('communications', 'Message')

    for conv in Conversation.objects.all():
        for user in conv.participants.all():
            last_msg = Message.objects.filter(
                conversation=conv,
                read_by=user
            ).order_by('-id').first()

            ConversationParticipant.objects.get_or_create(
                conversation=conv,
                user=user,
                defaults={
                    'last_read_message': last_msg,
                    'last_read_at': last_msg.created_at if last_msg else None,
                }
            )


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_genericcomment_unique_generic_comment_client_temp_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='شناسه همگام\u200cسازی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف\u200cشده (نرم)')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین خواندن')),
                ('is_muted', models.BooleanField(default=False, verbose_name='بی\u200cصدا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_memberships', to='communications.conversation', verbose_name='گفتگو')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_by_participants', to='communications.message', verbose_name='آخرین پیام خوانده\u200cشده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضو گفتگو',
                'verbose_name_plural': 'اعضای گفتگو',
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_participant'),
        ),
        migrations.RunPython(backfill_participants_and_read_state, reverse_code=migrations.RunPython.noop),
    ]
